### ISSUE TITLE
Data.tree How to create Nodes with same names 

### ISSUE THREAD

**Issue by varu2794** [gluc/data.tree#100]
I am using data.tree library for creating a tree structure.But it doesn't allow me to create nodes with same names.So please help me.

Or tell me the part of the code in the source code to change so that I can create nodes with same names

**Comment by gluc** [comment]
The data.tree library requires that siblings (i.e. children of the same node) have unique names. This is inherently built into the data structure and there's no quick fix for this, as all API functions depend on this. However, if you tell me what you want to achieve, I'm sure there's a way. For example, you can set arbitrary attributes on nodes that do not require to be unique. 

```
library(data.tree)
tree <- Node$new("1")
child1 <- tree$AddChild("2")
child2 <- tree$AddChild("3")
child1$customName <- "child"
child2$customName <- "child"
print(tree, 'customName')
```

This will print as:

```
  levelName customName
1     1               
2      ¦--2      child
3      °--3      child
```

**Comment by varu2794** [comment]
Actually I want children of the same have same names.
Or is there a way like I give id to each node with same name and id the being unique.

**Comment by gluc** [comment]
> Actually I want children of the same have same names.

As I said, that's not possible.

> Or is there a way like I give id to each node with same name and id the being unique.

Not sure what you mean. But if it means what I think it means, then it's what I showed in my example.

**Comment by varu2794** [comment]
Please tell me how to get the children of nodes having same names.

**Comment by ShKlinkenberg** [comment]
@gluc I also want to do something similar. I have setup a data frame table structure with Ids and and title as attributes. I am trying to make a statistics test selection tree as can be seen [here](https://shklinkenberg.github.io/statistical-test-selection/StatisticalTestSelectionScheme.html) "tool tip only works in chrome". The repository can be found [here](https://github.com/ShKlinkenberg/statistical-test-selection). For visualisation I would like tho have the title in the places of the ids. So a node description replacement would do the trick I think. 

Though I admit I'm not really sure I am using the correct approach for my goal.
