### ISSUE TITLE
Data.tree giving id to each node

### ISSUE THREAD

**Issue by varu2794** [gluc/data.tree#102]
Is there any way that I give id to every node as shown below.

library(new.tree)
first<-read.csv("/home/varun/Documents/R/ipfile.txt",sep = " ",header = TRUE)
parent<-Node$new("Root")
level<-parent$AddChild("hello",id=1)
level1<-parent$AddChild("hello",id=2)
print(parent)

Please Help

Or are there any tree libraries which can print duplicate nodes.

**Comment by gluc** [comment]
Currently, the name _is_ the id. But you can use a custom attribute, they don't need to be unique. For example:

```
tree <- Node$new("1", displayName = "parent")
tree$AddChild("2", displayName = "child")
tree$AddChild("3", displayName = "child")
print(tree, "displayName")
```

This will look like this:

```
  levelName displayName
1     1          parent
2      ¦--2       child
3      °--3       child
```
