### ISSUE TITLE
How to get the children of nodes which have same name?

### ISSUE THREAD

**Issue by varu2794** [gluc/data.tree#104]
I have nodes which have same name.They are not unique,but the children of the nodes are unique and they are not been plotted separately.So please tell me how to plot the names of the children whose parents have same name. 

Also tell me how to read a text file and populate a tree with each word as a node in a
 branch of tree.

**Comment by gluc** [comment]
Hi, not sure I understand. Could you pls be more explicit, e.g. with an example dataset? Thx.
