### ISSUE TITLE
question, use data.tree as backend for user specified conditional frequency tabulations (alternative to xtabs)

### ISSUE THREAD

**Issue by statsccpr** [gluc/data.tree#107]
Hi,

I've been having this simple idea for awhile, and i think data.tree would be a good backend to implement it in R.

Does anyone have advice on how to produce an output tree, where each leaf is a frequency count (conditional to its parent nodes). Might be related to https://github.com/gluc/data.tree/issues/21

The big picture is, this would be an alternative for a quick cross tabulation using `stats::xtabs()`

where the interface would be  `tree_freq(data,formula)`

Say,
```
`tree_freq(data=iris,  . ~ Species + (Sepal.Length | c(0.1,0.2) ) )`
```
will output a tree. 

The first parent node would be the three categories of `Species`, then sprouting `Sepal.Length` child nodes specified at the 3 intervals formed by the two cutpoints, `[min(Sepal.Length),0.1 ] U [0.1,0.2] U [0.2,max(Sepal.Length)]`

The data.tree [vignette](https://cran.r-project.org/web/packages/data.tree/vignettes/applications.html#id3-machine-learning)(classification tree) makes me believe this is do-able

The big difference from the id3 example is, what i'm proposing here does not involve 'learning / estimating' the cutpoints or 'important' variables. Instead, my proposal lets the user directly specify the order of the variables and the cutpoints (via a formula), then internally passes objects needed to data.tree

**Comment by gluc** [comment]
Yes, I think this is doable, though I'm not sure I understand the details. Could you maybe make an example of the target tree? Thx!
