### ISSUE TITLE
plot.Node does not pass through elipses to render_graph

### ISSUE THREAD

**Issue by jsta** [gluc/data.tree#109]
Running the following does not produce a plot with a title:

```
data(acme)
plot(acme, title = "Testing 123")
```

Pulling out the code from [plot.Node](https://github.com/gluc/data.tree/blob/a966edd42051814b45dd70e834301f94c7311b1a/R/node_plot.R#L10) does produce a plot with a title:

```
graph <- ToDiagrammeRGraph(acme, "climb", NULL)
DiagrammeR::render_graph(graph, output = "graph", title = "Testing 123")
```

**Comment by gluc** [comment]
Thx, implemented, but available on CRAN only with the next release (0.7.6, not yet scheduled).
