### ISSUE TITLE
Package load fails due to missing dependency

### ISSUE THREAD

**Issue by JanaJarecki** [gluc/data.tree#111]
Hi,

after installung data.tree and running library(data.tree) on Win 10, I get the error

> package or namespace load failed for ‘data.tree’: Objekt ‘cividis’ ist nicht von 'namespace:viridisLite' exportiert
> (object 'cividis' not exported by namespace:viridisLite.)

Solution:
I have to load the viridis package manually before loading data.tree (library(viridis), library(data.tree)) for the error to disappear.

Maybe include this in the load routine?

cheers
Jana

**Comment by vnijs** [comment]
@JanaJarecki Try installing the latest version of the DiagrammeR package which is most likely where the dependency is coming from

@gluc I had a similar issue with one of my packages. I'm pretty sure you just need to require a more recent version of DiagrammeR (e.g., >= 1.0.0)

**Comment by gluc** [comment]
Indeed @vnijs suggestions works. Thx a lot!
If I don't get any other requests within the next few days, I'll release to CRAN. In the mean time, pls make sure you have the latest DiagrammeR package available.
