### ISSUE TITLE
Moving converted nodes

### ISSUE THREAD

**Issue by enginetix** [gluc/data.tree#114]
Hello, 
When I create data tree nodes and convert to a dgr_graph I apply node potions using set_node_position I cannot get any nodes to move. I can move nodes using the internal example. Any tips for controlling the location of nodes (with or without conversion). My example is below:

Regards,

`
library(data.tree)
library(DiagrammeR)

acme <- Node$new("Acme Inc.")
accounting <- acme$AddChild("Accounting")$
  AddSibling("Research")$
  AddChild("New Labs")$
  parent$
  AddSibling("IT")$
  AddChild("Outsource")
print(acme)
plot(acme)

df <- ToDiagrammeRGraph(acme)
render_graph(df)

df <-
  df %>%
  set_node_position(node=1,x=1,y=1) %>%
  set_node_position(node=2,x=1,y=2) %>%
  set_node_position(node=3,x=2,y=3) %>%
  set_node_position(node=4,x=3,y=4) %>%
  set_node_position(node=5,x=4,y=5) %>%
  set_node_position(node=6,x=5,y=6)

df %>%
  get_node_df()

render_graph(df) 
`

**Comment by gluc** [comment]
I'm afraid that's a DiagrammeR issue. Can you please ask the question over at DiagrammeR? Thx!
