### ISSUE TITLE
Generic `plot()` does not work when Node is created from `tibble`

### ISSUE THREAD

**Issue by gueyenono** [gluc/data.tree#115]
This issue is of particular importance to those who regularly use the `tidyverse`. By that I mean those who import their data with the `readr` package and keep their data in the `tibble` format.

Here I create a simple `data.frame`, convert it into a `Node` object and then plot it. It works!

```
tree_data <- data.frame(
from = c("President", "President"),
to = c("Vice-President 1", "Vice-President 2")
)
nodes <- FromDataFrameNetwork(tree_data)
plot(nodes)
```
The issue is that when the original data is in a `tibble` prior to converting it into a `Node` object, the `plot()` function returns an error:

```
library(tibble)
tree_data_tbl <- as_tibble(tree_data)
nodes_2 <- FromDataFrameNetwork(tree_data_tbl)
plot(nodes_2)

Error in do.call(create_node_df, c(n = length(tr), myargs)) : 
  second argument must be a list
```

**Comment by gluc** [comment]
will be fixed in next release.
In the mean-time, just workaround with as.data.frame(tree_data_tbl)
