### ISSUE TITLE
as.Node() failing

### ISSUE THREAD

**Issue by JestonBlu** [gluc/data.tree#118]
I'm running through the tutorial on converting a data.frame to a tree and I'm getting an unexpected error when I try to run the sample code.

```r
library(data.tree)
GNI2014$continent <- as.character(GNI2014$continent)
GNI2014$pathString <- paste("world", GNI2014$continent, GNI2014$country, sep = "/")
tree <- as.Node(GNI2014[,])
```

returns
```
Error in Node$new(paths[1], check) : attempt to apply non-function
```

Does the tutorial need to be updated or is this a potential bug?

**Comment by JestonBlu** [comment]
This was a non issue... i had an something in my environment that was causing it to fail. When I cleared my objects it worked fine.

**Comment by gluc** [comment]
Glad to hear. 
Just for others seeing this example: It's not self-contained. GNI2014 is in the treemap package, and not in data.tree.
