### ISSUE TITLE
question / suggestion on intro document

### ISSUE THREAD

**Issue by dan-reznik** [gluc/data.tree#120]
hi christopher -- i am making my way thru the [intro document](https://cran.r-project.org/web/packages/data.tree/vignettes/data.tree.html). I noticed you use global variables in the "Custom fields" section, specifically, in this code:

```{r}
software$cost <- 1000000
standards$cost <- 500000
newProductLine$cost <- 2000000
newLabs$cost <- 750000
outsource$cost <- 400000
agile$cost <- 250000
goToR$cost <- 50000

software$p <- 0.5
standards$p <- 0.75
newProductLine$p <- 0.25
newLabs$p <- 0.9
outsource$p <- 0.2
agile$p <- 0.05
goToR$p <- 1
print(acme, "cost", "p")
```
I understand "software" and "agile" are global variables defined at the very top. May I suggest a rewrite of this portion so each line only depends on the "acme" tree and not on globals?

**Comment by gluc** [comment]
Thx a lot for this input. By putting it into a global variable, and then changing it, I wanted to stress the fact that data.tree has reference-semantics. But you're probably right, it's more confusing than educative ;-) Will change for the next version. Thx again for reading attentively and providing constructive feedback!
I will leave it open so I won't forget.

**Comment by dan-reznik** [comment]
thanks to you for building a great library and writing such great docs

dan
