### ISSUE TITLE
Changing levelName in tree structure

### ISSUE THREAD

**Issue by saulius88** [gluc/data.tree#121]
Hi, 

I would like to be able to change level names from unique IDs to human-readable tags in my tree structure. A sample of the tree:
> print(tjpCPI, "CPI.Tag")
                                levelName                          CPI.Tag
1   378257447                                                          CPI
2    ¦--378257497                                                     Food
3    ¦   ¦--378259447                                              Cereals
4    ¦   ¦   ¦--378259457                                             Rice
5    ¦   ¦   ¦   ¦--378259467                                Non Glutinous
6    ¦   ¦   ¦   ¦   ¦--378259477                                   Rice-A
7    ¦   ¦   ¦   ¦   °--378259487                                   Rice-B
8    ¦   ¦   ¦   °--378259497                                    Glutinous

I would like to swap the IDs in level names to the readable CPI.Tags

I am trying to use the Do function:
tjpCPI$Do(function(node) node$levelName<-node$CPI.Tag)
but that throws an error of:
Error in (function ()  : unused argument (quote("CPI"))

How might I go about changing the levelNames?

Thanks in advance!

**Comment by gluc** [comment]
As stated in the documentation, the levelName is read only and not intended for use by package users.
If you would like replace the IDs with CPI.Tags, you can do so by changing the name of the Nodes, though the Names of siblings must be unique within a parent. You can still keep an $id attributed on the nodes for the IDs.
