### ISSUE TITLE
FromDataFrameNetwork

### ISSUE THREAD

**Issue by prab0509** [gluc/data.tree#130]
FromDataFrameNetwork converts the dataframe to a hierarchical network structure. I takes too long to convert to a network object when the number of points is too high. Is there a way to speed up the process.

**Comment by gluc** [comment]
What expectations do you have? Specifically size of data-frame, number of columns, and expected time. Ideally, pls provide a reproducible example with current timing.
Finally, be advised that data.tree has not been optimised for speed and large data sets. However, if you see quick wins, then I'm very open to pull requests!

**Comment by prab0509** [comment]
The data frame is approx 46k rows with 4 columns. I am using FromDataFrameNetwork functionality to convert it into a Network. Below is a part of the code that i am using.

datax<<-FromDataFrameNetwork(chtData)

chtData is my data frame with 46k rows and 4 columns. This step itself takes somewhere around 10 mins. Please suggest if you have any ideas to optimize the function.

**Comment by gluc** [comment]
Unfortunately, there are currently no plans to improve speed and support for large trees.
