### ISSUE TITLE
List of lists to Node: simpleList saves only leaves names, and explicitList returns a one-node 'root' node

### ISSUE THREAD

**Issue by earnaud** [gluc/data.tree#132]
Hello,
my title sums it up, but here's the thing in detail:
1/ I parse xsd files into a list with 'XML2' library. :heavy_check_mark: 
2/ I take a sublist of the first list. :heavy_check_mark: 
3/ I want to turn it into data.tree. I try:
a/ simpleList: the non-leaf nodes are unnamed.
b/ explicitList: this only returns me a node named "root".
I'll upload an example in the next few minutes in my git, see the comments.

**Comment by earnaud** [comment]
You can have a look at ```xsdExplorer.R``` (which is a rough draft script) in https://github.com/earnaud/R-EMD/tree/master/shinyApp/_infoBuilder. 
Thanks you by advance for any help you can provide.

**Comment by gluc** [comment]
Sorry for the late reply. Is this still an issue for you?
