### ISSUE TITLE
Move a branch

### ISSUE THREAD

**Issue by alexiosg** [gluc/data.tree#133]
Hi, is there any easy way of moving an entire branch to a new node?

For instance, if a leaf has the following path Acme/Accounting/IT/Office1, how would I move the branch "Accounting/IT/Office1" under a new node I created in Acme (e.g. under Acme/Other/Accounting/IT/Office1)? I've been able to move single leafs (eliminating their position from the old location), but I have not found an easy way to move a full branch. I could ofcourse rebuild the tree by changing the pathString in the original dataset, but was wondering if there was another way.

Thanks!

**Comment by thothal** [comment]
This is how I would do it:

```R
library(data.tree)
data(acme)
acme$Accounting$AddChildNode(Clone(acme$IT))
acme$RemoveChild("IT")
acme
#                           levelName
# 1  Acme Inc.                       
# 2   ¦--Accounting                  
# 3   ¦   ¦--New Software            
# 4   ¦   ¦--New Accounting Standards
# 5   ¦   °--IT                      
# 6   ¦       ¦--Outsource           
# 7   ¦       ¦--Go agile            
# 8   ¦       °--Switch to R         
# 9   °--Research                    
# 10      ¦--New Product Line        
# 11      °--New Labs     
```

You need to clone the sub-branch to make sure that you get a new reference, otherwise you will mess up your whole tree.

**Comment by gluc** [comment]
Thx @thothal , that's exactly how I would do it :-)
