### ISSUE TITLE
TrainID3 method removed from data.tree package??

### ISSUE THREAD

**Issue by agilebean** [gluc/data.tree#134]
I am really confused by many internet resources citing the use of the data.tree::TrainID3 method in extensive examples like [here](https://mran.microsoft.com/snapshot/2015-04-19/web/packages/data.tree/vignettes/ID3.html#the-id3-algorithm)

There is even a CRAN page that documents the [TrainID3 method](https://cran.r-project.org/web/packages/data.tree/vignettes/applications.html#id3-machine-learning).

Nevertheless, calling this method
```
library(data.tree)
tree.id3 <- TrainID3(node = Node$new("titanic"), 
                     data = training.set) %T>% print
```

shows it is not contained in the data.tree library (just updated again today, 2019-04-25):
```
Error in TrainID3(node = Node$new("titanic"), data = training.set) : 
  could not find function "TrainID3"
```

I understand the vignette is up-to-date because it does not contain any reference to the ID3 method. But can someone enlighten me whether this is just a different library or that it was removed and why? 
I didn't find any release notes to scroll through.

**Comment by gluc** [comment]
ID3 was never part of the package. It was, however, always part of the examples applications in the vignette. If you want to use it, you can copy and paste the code from the vignette.

**Comment by agilebean** [comment]
Thanks a lot for the clarification!
I realized that the ID3 codes uses methods from the data.tree package to *illustrate* its usage...
