### ISSUE TITLE
Plot doesn't like quotation in name of node even when escaped

### ISSUE THREAD

**Issue by zrodriguez89** [gluc/data.tree#137]
Issue specifically comes from line 8 below:
 
empiricVett <- epRatio$AddChild("P2: \\"Empirically vetted\\" composite")

When remove quotation marks everything will plot fine. Printing works fine. It's the plot that throws a syntax error. Any way to resolve this?

behaveData <- Node$new("Data")
cyclePhase <- behaveData$AddChild("P1: Cycle phase")
  wholeData <- cyclePhase$AddChild("Whole dataset N = 157")
  lhValidated <- cyclePhase$AddChild("LH validated dataset n = 112")
steroid <- behaveData$AddChild("P1: Steroid hormones")
  logHormones <- steroid$AddChild("Log-transformed hormones")
    epRatio <- logHormones$AddChild("E/P ratio") 
      empiricVett <- epRatio$AddChild("P2: \\"Empirically vetted\\" composite")
        controlBMI <- empiricVett$AddChild("Controlling for BMI interaction effect")
          threeInteract <- controlBMI$AddChild("Three-way interaction with relationship status")
          twoInteract <- controlBMI$AddChild("Two-way interaction without relationship status")
        noAddControl <- empiricVett$AddChild("Not adding a control variable")
          threeInteract <- noAddControl$AddChild("Three-way interaction with relationship status")
          twoInteract <- noAddControl$AddChild("Two-way interaction without relationship status")

print(behaveData)
plot(behaveData)

**Comment by gluc** [comment]
Fixed, thx @thothal !
