### ISSUE TITLE
Why Does Cumulate Consider only "left" siblings?

### ISSUE THREAD

**Issue by thothal** [gluc/data.tree#138]
I was hoping to use  `Cumulate` to, well, accumulate a certain slot from all siblings and was surprised that this did not work as (I) intended:

```R
library(data.tree)
mt <- as.Node(list(name = "#", N = list(SN1 = list(SN2 = list(C1 = list(id = 1L), 
    C2 = list(id = 2L, C3 = list(id = 3L)))), SN3 = list(C4 = list(
    id = 4L), C5 = list(id = 5)))))

Cumulate(mt$N$SN3$C4, "id", c)
# C4
#  4
Cumulate(mt$N$SN3$C5, "id", c)
# C4 C5 
#  4  5 
```

I then read the help of `Cumulate` and it clearly states that

> For example, you can sum up values of siblings before this ‘Node’.

And looking at the source code of `Cumulate` confirms that
```R
# [...]
pos <- node$position
nodes <- node$parent$children[1:pos]
# [...]
```
I have a hard time thinking of a use case for that versus the IMHO more relevant use case that I want to accumulate the values of _all_ the siblings.

Thus, my questions:
* Is this behavior intentional? What is the use case for this? At least for me the name is then rather misleading, as I would suspect a `cumulate` function to accumulate all the siblings and not only the "left" siblings.
* What is the proposed way to accumulate values from all siblings? A simple `lapply(node$children, ...)`?
* Would it then make sense to provide a function which helps you for this pattern?

**Comment by gluc** [comment]
The idea for the `Cumulate` is similar to `cumsum` etc., i.e. to provide e.g. a running sum. You can run an operation on all siblings by using `Aggregate` on the parent, e.g. 
```
Aggregate(mt$N$SN3, "id", c)
[1] 4 5
```
