### ISSUE TITLE
Prune tree (as.list) without altering

### ISSUE THREAD

**Issue by seafood-express** [gluc/data.tree#142]
What options do I have to prune a tree without altering it? I found [this answer on stackoverflow](https://stackoverflow.com/questions/46052725/r-pruning-data-tree-without-altering), but unfortunately I need to save the pruned tree as a list and `as.list.Node()` doesn't accept a `pruneFun`.
Thanks for the great package!

**Comment by gluc** [comment]
If it's not too big, you can first clone it, and then prune the clone.

**Comment by seafood-express** [comment]
This is what I'm currently doing but I would like to save resources since the tree is quite large and the app has performance issues because of it. Is there no other way?

**Comment by gluc** [comment]
Not currently, but I guess it would not be too difficult to build it into as.list.Node(). One would simply have to add a if condition to https://github.com/gluc/data.tree/blob/master/R/node_conversion_list.R#L140
Let me think about it. Or if you need it urgently, pls consider creating a pull request (I'm planning to release a new version to CRAN soon).
