### ISSUE TITLE
Reduce the dependency on DiagrammeR

### ISSUE THREAD

**Issue by russHyde** [gluc/data.tree#143]
data.tree 'Imports' DiagrammeR and DiagrammeR brings a lot of dependencies with it.

Would you welcome a PR that moves the dependency on DiagrammeR from Imports to Suggests, so that we can use the data.tree datastructures without installing DiagrammeR? This would require that `data.tree::ToDiagrammeRGraph()` is rewritten slightly to include a namespace check.

Kind regards

**Comment by gluc** [comment]
Absolutely, that's a great idea, I'm very supportive!

**Comment by gluc** [comment]
Thx for the PR!
