### ISSUE TITLE
Dual dimension data tree with custom fields as data tree

### ISSUE THREAD

**Issue by b4D8** [gluc/data.tree#146]
Hi! Great package, helps me a lot, thanks ! 
This repo isn't very active lately, I really hope the package won't be discontinued.

I am primarily using data.tree for accounting purposes, with nodes being accounts and custom fields dates.
A great enhancement for this use case would be to be able to have custom fields to be a data tree as well.
More explicitly, the custom field could then be something like time$2020$may$25 allowing one to store the data on a day basis and print them on a year basis for instance (but applications go way beyond this simple example).

**Comment by gluc** [comment]
Hi, thx for using data.tree. Indeed, the package has reached a level of maturity that doesn't require daily commits anymore. But rest assured that there are currently no plans to discontinue maintenance.
Regarding your request, I'm not so sure I fully understand. data.trees already support attributes, and I believe that's what you mean by custom fields. I believe adding a data.tree as an attribute to a node of another data.tree is also already possible. But maybe I'm missing the point. If you can describe in more detail, I'm happy to provide an example or look into a possible feature request. Thx!

**Comment by skymonio** [comment]
Thanks for your answer. Good to know I can rely on this package! Sorry for doubting you 😅

So I think you definitely got my point. I mixed names while refering to [the documentation](https://cran.r-project.org/web/packages/data.tree/vignettes/data.tree.html#custom-fields) that uses them both at some point.

Anyway, I didn't realized that this was already possible. That's great! I probably have some more digging to do before I can use the full potential of the library. 

Could you please show me the way on how to use a time data tree (in the form of year$month$day) as an attribute of an accounting data tree (just like the acme sample used in the documentation) ? 

What I would like is to put a value at the intersection of these two data trees and then get the values to aggregate up to the roots.

Thanks for your help!

**Comment by gluc** [comment]
Hey, happy to look into this, but not sure I fully understand what you want to do. Can you describe in more detail? Thx.

**Comment by gluc** [comment]
I'm assuming you found a solution :-)
