### ISSUE TITLE
root of the tree after converting phylo

### ISSUE THREAD

**Issue by ETaSky** [gluc/data.tree#148]
Hello, thank you for this great tool and documents! I am currently having a problem with rooting the tree created by data.tree from a data frame. Here is what I did:
```
library(ape)
data(acme)
acmephylo <- as.phylo(acme)
is.rooted(acmephylo)  # the output is FALSE
root.phylo(acmephylo, node = 8)  # this still output a tree that unrooted
```

Could you help with this?

Thanks!

**Comment by ETaSky** [comment]
After doing some research, a temporary work around is to convert the tree firstly to newick format, appending a branch length for the root, and read it back:
```
library(ape)
library(data.tree)
library(dplyr)

library(ape)
data(acme)
acmephylo <- acme %>% ToNewick() %>% gsub(pattern = "Acme_Inc.", replacement = "Acme_Inc.:0", fixed = T)
tt <-read.tree(text = acmephylo)
is.rooted(tt)  # TRUE
```
While doing the research, I feel this problem may be rooted in the ape package (?). Because the acme dataset is actually from ape.

B

**Comment by gluc** [comment]
Thx for your question, and sorry for the late reply. I'm not a specialist for the ape package, but here a few points to note:

1. acme is not from ape, as you mentioned, but it's the sample data for data.tree. It's not by any means phylogenetic data.
2. "rooted" in ape is defined as: `A tree is considered rooted if either only two branches connect to the root, or if there is a root.edge element. In all other cases, is.rooted returns FALSE.`
