### ISSUE TITLE
Partial argument for R6 Node class

### ISSUE THREAD

**Issue by oliverbeagley** [gluc/data.tree#149]
I have `options(warnPartialMatchArgs = TRUE)` set in my `.Rprofile` which has printed a partial argument warning during the install to v1.0.0

The argument in question is here:
https://github.com/gluc/data.tree/blob/ded55fd3b20bacb83480764752b1d7273698bd18/R/node.R#L123

It should be `lock_objects`

**Comment by gluc** [comment]
Thx for this, will look into it.

**Comment by gluc** [comment]
Thx a lot, fixed now in dev, will be rolled out with the next release.
...wondering how this could have gone unnoticed for 5 years???
