### ISSUE TITLE
Print or Get filterFun error when nodes have missing attribute values

### ISSUE THREAD

**Issue by py** [gluc/data.tree#151]
First - thank you for this package. It has allowed me to explore tree data structures with the tools I already use - R!

The example below highlights an issue I am having. I am trying to count nodes with specific attributes (e.g. title of VP) and aggregate them across the levels of the tree (e.g. what % of Carol's span is VP's?). In the real data I am using, there are some nodes with missing or NA attributes. This causes the error illustrated below. 
```
Error in if (length(filterFun) == 0 || filterFun(node)) { : 
  missing value where TRUE/FALSE needed
```
Most of the examples in the documentation [1] use `pruneFun` or `filterFun` that also include the `isLeaf` criterion, so this particular issue does not occur. 

What is the expected behavior in this situation? What is the recommended approach to handling NA or blank attributes so as to avoid this error and return a result? 

```R
library(data.tree)
# Create org chart tree
bob <- Node$new("Bob")
  carol <- bob$AddChild("Carol")
    tim <- carol$AddChild("Tim")
  carlo <- bob$AddChild("Carlo")
    tom <- carlo$AddChild("Tom")
# Add title attribute
bob$title <- "CEO"
bob$Carol$title <- "SVP"
bob$Carlo$title <- "VP"
bob$Carol$Tim$title <- "Manager"
bob$Carlo$Tom$title <- "Manager"

# Find all the VP's - This works because every node has title attribute
print(bob, "title",
      filterFun = function(x) x$title == "VP"
)

# Add Susan node but do not give her a title attribute
bob$AddChild("Susan")
# Now finding VP nodes has error because there is an a node without a title attribute
print(bob, "title",
      filterFun = function(x) x$title == "VP"
)

# Give Susan a title and try again
bob$Susan$title <- "VP"
print(bob, "title",
      filterFun = function(x) x$title == "VP"
)
````

1: https://cran.r-project.org/web/packages/data.tree/vignettes/data.tree.html

**Comment by gluc** [comment]
Hey Peter, thx for using data.tree! The filterFun can be any function, so you can test for availability of an attribute, e.g. like this:

```R
print(bob, "title",
      filterFun = function(x) !is.null(x$title) && x$title == "VP"
)
```
