### ISSUE TITLE
Support for converting C5.0 objects to data.tree?

### ISSUE THREAD

**Issue by AndyBunn** [gluc/data.tree#155]
Hello, `{data.tree}` is amazing. I'm floored by the dedication to this package and eager to learn more about it.

I've inherited a project where a colleague has passed on several objects from `{C50}`. I'm fairly new to hierarchical data structures and was hoping to convert these for use in `{data.tree}` for visualization. Can anybody get started by showing how `sppTree` can be coerced into something `{data.tree}` understands so I can make a prettier plot than the plot function in `{C50}`? 

```
library(C50)
library(data.tree)
data(iris)
sppTree <- C5.0(Species~.,data=iris)
```

**Comment by gluc** [comment]
Thx! Will look into it...

**Comment by AndyBunn** [comment]
Appreciate it very much!

**Comment by gluc** [comment]
You can convert C50 to party object like this:

```
library(C50)
library(data.tree)
data(iris)
sppTree <- C5.0(Species~.,data=iris)
party <- as.party.C5.0(sppTree)
dt <- as.Node(party)
plot(dt)
```
I don't know C50, so not sure how much information is lost:

```
print(dt, dt$attributesAll)

      levelName        data     fitted    nodeinfo   partyinfo       split splitlevels  splitname       terms  splitLevel
1 1                    data      terms splitlevels   partyinfo      fitted  splitLevel  splitname       split    nodeinfo
2  ¦--2              fitted splitLevel   splitname       split    nodeinfo        data      terms splitlevels   partyinfo
3  °--3            nodeinfo       data       terms splitlevels   partyinfo      fitted splitLevel   splitname       split
4      ¦--4       partyinfo     fitted  splitLevel   splitname       split    nodeinfo       data       terms splitlevels
5      ¦   ¦--5       split   nodeinfo        data       terms splitlevels   partyinfo     fitted  splitLevel   splitname
6      ¦   °--6 splitlevels  partyinfo      fitted  splitLevel   splitname       split   nodeinfo        data       terms
7      °--7       splitname      split    nodeinfo        data       terms splitlevels  partyinfo      fitted  splitLevel
```
However, if you're courageous enough, you might want to have a go at writing a direct converter from C50 to Node (`as.Node.C5.0`). Happy to accept a pull request :-)

**Comment by AndyBunn** [comment]
With a little sleuthing, it seems like the `data` attribute is lost in `dt`. E.g.,:
`print(dt,` "data")`
But the conversion to `party` has all the classification info so it might be some wrinkle in the formatting. Running `plot(party)` above produces the right tree. Just not as attractive or flexible as I was hoping. I'll try to find time to look in a little more depth at `as.Node.party`.
