### ISSUE TITLE
data.tree within targets: failure: length > 1 in coercion to logical

### ISSUE THREAD

**Issue by jasonlerch** [gluc/data.tree#156]
Got the following error when using data.tree inside targets (or drake, I would guess): failure: length > 1 in coercion to logical. Not sure why I only get it when used inside targets; no error if using it on the console or in standard scripts.

Error occurs inside the aggregate function:

`if (length(v) > 0 && !is.na(v)) return(v)`

This fixes it:

`if (length(v) > 0 && !any(is.na(v))) return(v)`

Full diff as follows:

```
--- a/R/node_methods.R
+++ b/R/node_methods.R
@@ -117,7 +117,7 @@ Aggregate = function(node,
   values <- sapply(node$children,
                    function(x) {
                      v <- GetAttribute(x, attribute, format = identity, ...)
-                     if (length(v) > 0 && !is.na(v)) return(v)
+                     if (length(v) > 0 && !any(is.na(v))) return(v)
                      Aggregate(x, attribute, aggFun, ...)
                    })
   result <- unname(aggFun(values))
```

**Comment by gluc** [comment]
Hey, it's very hard to help you with this one. If you can provide me a reproducible example and a step-by-step guide that allows me to reproduce, I will look into it. Thx!
