### ISSUE TITLE
Name Duplicated are Automatically Deleted

### ISSUE THREAD

**Issue by DirkAmp** [gluc/data.tree#163]
I like this package very much, thanks!

Currently, I observed the automatic remove of duplicated children. Here is an example with version 1.0.0 of `data.tree`:

    lst = list(name = "Bla", A = "A", children = list(list(name = "Bla", B = "B"), list(name = "Bla", C = "C")))
    FromListExplicit(lst)

Result:

      levelName
    1   Bla    
    2    °--Bla

The list element with `C = "C"` is removed. Is this correct? If yes, how can I get the complete list in the `data.tree` structure?

**Comment by gluc** [comment]
Yes, this is expected behavior. The node names need to be unique among siblings.
