### ISSUE TITLE
Subset tree by index number (when printed)

### ISSUE THREAD

**Issue by kstoltz1** [gluc/data.tree#165]
This seems like a very simple question, I haven't been able to find a straightforward answer though.

Can you subset a data.tree by the line index to obtain the value for that line?

I.e., could I obtain the highlighted value in the snapshot below by subsetting my "mytree" data.tree object in a manner like `mytree[12]`?
<img width="914" alt="image" src="https://user-images.githubusercontent.com/48219386/211062634-8d2bca91-7c75-497c-99eb-67f5d9126f92.png">

I've found that you can change it to a dataframe, and then subset by row number:
<img width="991" alt="image" src="https://user-images.githubusercontent.com/48219386/211063034-6b2a1176-0f4b-49de-91f7-3cef954698f2.png">
but then the output includes the leading and trailing whitespace and formatting characters.

If anyone is aware of a more elegant solution I would appreciate it, thanks!

**Comment by gluc** [comment]
You can export it to a data frame, including the attribute `name`, and then fetch the name instead:

```
data(acme)
ToDataFrameTree(acme, "name")
```
