### ISSUE TITLE
docs on igraph conversion

### ISSUE THREAD

**Issue by nick-youngblut** [gluc/data.tree#168]
The data.tree manual states:

>Finally, easy conversion options *from and to* JSON, YAML, igraph, and more exist.

...and the docs are quite clear on `data.tree <--> JSON/YAML` conversions (and conversion to igraph); however, the docs are not very clear on conversion *from* igraph *to* data.tree. One cannot simply use `as.Node()`, since that generates the error:

```
Error in UseMethod("as.Node") : 
  no applicable method for 'as.Node' applied to an object of class "igraph"
````

**Comment by gluc** [comment]
Sorry for the late reply. Unfortunately, conversion from `Node` to `igraph` is not implemented. Thanks for pointing this out. I made it clear in the documentation.
