### ISSUE TITLE
another  use of `data.tree`

### ISSUE THREAD

**Issue by timelyportfolio** [gluc/data.tree#18]
Thanks so much for the great package and even better continued iteration and improvement.  I thought you might like to know that I have incorporated `data.tree` into [`d3treeR`](http://www.buildingwidgets.com/blog/2015/7/17/week-28-d3treer) which likely will be rolled into `treemap`.   The  code is in https://github.com/timelyportfolio/d3treeR/blob/master/R/converters.R.

**Comment by gluc** [comment]
Great, thanks a lot. Glad I did something useful! 
Looks indeed like a good use. I played around a bit with d3treeR, and it's pretty neat!
