### ISSUE TITLE
Error in attribute(node, ...) : unused argument (assign = "expectedCost")

### ISSUE THREAD

**Issue by vnijs** [gluc/data.tree#19]
I'm trying to use data.tree to calculate the EMV of a decision tree with decision and event nodes. After working through the vignette I believe I would have to use post-order move and also the `assign` option in `Get`. However, when I try to use that feature I get the error message below when using the version of data.tree on GitHub. Has this option changed?

`
> acme$Get(function(x) x$p * x$cost, assign = "expectedCost")
Error in attribute(node, ...) : unused argument (assign = "expectedCost")
`

**Comment by gluc** [comment]
Yes, the assign parameter has been replaced by the new Do method. See https://github.com/gluc/data.tree/blob/master/NEWS for details.
So, instead, you would now do:`

`
acme$Do(function(x) x$expectedCost <- x$p * x$cost)
`

You might also be interested in this decision tree example, which I presented at the useR conference in June. I have just updated it to keep up with the latest developments in data.tree: https://github.com/gluc/useR15/blob/master/01_showcase/02_decision_tree.R

**Comment by vnijs** [comment]
This is fantastic!! Exactly what I was looking for. Using yaml to source the tree was a great idea. Thanks @gluc.

FYI I have a shiny app that I use for several class and I added an interface to data.tree for decision trees. See link below (Decide > Decision tree). Click the `Calculate` button to see the output. Comments & suggestions welcome. Please also let me know if the attribution in the help file (? icon) is ok.

http://vnijs.rady.ucsd.edu:3838/quant/?SSUID=c4e9c5f289

Code here: https://github.com/vnijs/radiant/blob/master/R/dtree.R

Note that I haven't included any plots yet. In your code you used the ape packages. However, I have been planning to do something with @rich-iannone's [DiagrammeR](https://github.com/rich-iannone/DiagrammeR) package and it seems a great fit with data.tree. Before I start down this path, however, I thought it might be worthwhile checking if this is something you have perhaps already looked into. The intent would be something like the image attached below:

![image](https://cloud.githubusercontent.com/assets/2998956/8898733/1924981c-33df-11e5-9b88-f9886006886b.png)

FYI Two minor points I noticed as I was using and building data.tree:

Cloning leads to a warning:
jl_init <- Clone(jl)
## Warning messages: 1: In res[fieldName] <- field : number of items to replace is not a multiple of replacement length

When building data.tree:
`R6Class Node: 'lock' argument has been renamed to 'lock_objects' as of version 2.1.This code will continue to work, but the 'lock' option will be removed in a later version of R6`

**Comment by vnijs** [comment]
I played around with the plotting code you posted as part of the presentation. This is what I have sofar. The labels are the main issue i see. I'm curious to see sure how DiagrammeR would deal with these. Cope updates here: 

https://github.com/vnijs/radiant/blob/master/R/dtree.R#L113-L154

![image](https://cloud.githubusercontent.com/assets/2998956/8899309/a0a338b8-33e7-11e5-90fa-933da0b42a89.png)

**Comment by gluc** [comment]
Wow, pretty impressed by Radiant! And to see data.tree in it would make me very proud!

I have not been looking into DiagrammeR so far, but, yes, it looks like this might be quite a good fit indeed. Ape was not built for this, and it was used by this example for no particular reason at all. I am quite busy today and tomorrow, but will look into it asap. In the mean time, if you want to move forward, pls do. I would also be very open for contributions to data.tree ;-)

Thanks also for letting me know about the warnings, looks like I need to update R6...

**Comment by vnijs** [comment]
Thanks for the comments @gluc. Made some progress with mermaid in Diagrammer images below. Code also below. 

http://vnijs.github.io/radiant/quant/dtree/mermaid-dtree-init.html
http://vnijs.github.io/radiant/quant/dtree/mermaid-dtree-final.html

Final step will be to go from this [list of two data.tree objects](https://www.dropbox.com/s/8kr8pb95ntuc82z/quant_job.rda?dl=0) to the two graphs linked above. I think it is best-practice to [create the string for mermaid using paste](http://www.rdocumentation.org/packages/DiagrammeR/functions/mermaid) but I asked a question about this in an [issue for Diagrammer](https://github.com/rich-iannone/DiagrammeR/issues/116#issuecomment-125329636). Comments/suggestion on how to best make the last step would be much appreciated.

```r
library(DiagrammeR); library(magrittr)

mermaid("
graph LR
        A[ ] --> |Accept John's Offer| B[$12,000]
        A --> |Reject John's Offer |C(( ))
        C --> |Offer from Vanessa 0.6| D[ ]
        D --> |Accept Vanessa's Offer| E[$14,000]
        D --> |Reject Vanessa's Offer| F(( ))
        C --> |No Offer from Vanessa 0.4| G(( ))
        G --> |Salary 1 0.05| H[$21,600]
        G --> |Salary 2 0.25| I[$16,800]
        G --> |Salary 3 0.40| J[$12,800]
        G --> |Salary 4 0.25| K[$6,000]
        G --> |Salary 5 0.05| L[$0]

        F --> |Salary 1 0.05| M[$21,600]
        F --> |Salary 2 0.25| N[$16,800]
        F --> |Salary 3 0.40| O[$12,800]
        F --> |Salary 4 0.25| P[$6,000]
        F --> |Salary 5 0.05| Q[$0]

        classDef default fill:none, bg:none, stroke-width:0px;
 	      classDef decision fill:#9f6,stroke:#333,stroke-width:1px;
 	      classDef chance fill:red,stroke:#333,stroke-width:1px;
	 	    class A,D decision;
	 	    class C,G,F chance;
")

mermaid("
graph LR
        A[$13,032] --> |Accept John's Offer| B[$12,000]
        A ==> |Reject John's Offer |C(($13,032))
        C --> |Offer from Vanessa 0.6| D[$14,000]
        D ==> |Accept Vanessa's Offer| E[$14,000]
        D --> |Reject Vanessa's Offer| F(($11,580))
        C --> |No Offer from Vanessa 0.4| G(($11,580))
        G --> |Salary 1 0.05| H[$21,600]
        G --> |Salary 2 0.25| I[$16,800]
        G --> |Salary 3 0.40| J[$12,800]
        G --> |Salary 4 0.25| K[$6,000]
        G --> |Salary 5 0.05| L[$0]

        F --> |Salary 1 0.05| M[$21,600]
        F --> |Salary 2 0.25| N[$16,800]
        F --> |Salary 3 0.40| O[$12,800]
        F --> |Salary 4 0.25| P[$6,000]
        F --> |Salary 5 0.05| Q[$0]

        classDef default fill:none, bg:none, stroke-width:0px;
        classDef decision fill:#9f6,stroke:#333,stroke-width:1px;
        classDef chance fill:red,stroke:#333,stroke-width:1px;
        class A,D decision;
        class C,G,F chance;
        ")
```

**Comment by vnijs** [comment]
@gluc I worked on this today but had trouble getting the outputs I needed while traversing the data.tree. Could you give some tips on how to get the different labels, names, and values as you loop through the data.tree? For example, how do you get a vector of node child names? I tried different things but must be missing something obvious.

**Comment by gluc** [comment]
Thanks for the bug reports, I fixed them.
Regarding mermaid: that's pretty cool, actually. Here's a gist with the code to get it working: https://gist.github.com/gluc/79ef7a0e747f217ca45e

**Comment by vnijs** [comment]
That was incredibly useful @gluc. Thank you! I had to make a few adjustment to get it to work with other examples but is working nicely now for both the initial tree and the solved tree. Very happy with the results sofar. For an example of the initial implementation see

http://vnijs.rady.ucsd.edu:3838/quant/?SSUID=a3a383df34

Press the `Calculate` button in Decide > Decision trees > Plot

One thing I would love to add is the ability to calculate (conditional) terminal probabilities when they are dependent on, e.g., some type of test or research. You can do the calculations beforehand and then plug-in the correct probabilities of course but a general solution strategy would be really valuable. Have you perhaps seen examples of algorithms (in R) that do this? For an example of that I'm talking about see: http://petrowiki.org/Decision_tree_analysis
