### ISSUE TITLE
print data.tree without row numbers (names) and without 'labelName'

### ISSUE THREAD

**Issue by vnijs** [gluc/data.tree#20]
When printing a data.tree object row numbers and 'levelName' are shown. Can this be turned off? I tried using Get to show levelName but then the alignment gets messed-up.

**Comment by gluc** [comment]
Actually, print internally just creates a data.frame which is printed, and nothing stops you from doing that yourself. E.g.

`
library(data.tree)
data(acme)
t <- Traverse(acme)
df <- data.frame(Get(t, "name"), Get(t, "cost"))
print(df, row.names = FALSE)
`

**Comment by vnijs** [comment]
Thanks @gluc! I had been trying the print.Node and couldn't get that to work at all. Using `Traverse`, `format`, and `print(., row.names = FALSE)` I got most of the way there. However, using `row.names = Get(jl,"levelName"))` was the best solution for me. Full function used in Radiant below:

```r
  format_dtree <- function(jl) {
    ## set parent type
    nt <- jl$Get(function(x) x$parent$type)
    jl$Set(ptype = nt)

    Traverse(jl) %>%
      {data.frame(Probability = Get(., "p", format = FormatPercent),
        Payoff = Get(., "payoff", format = print_money),
        Type = Get(., "ptype", format = rm_terminal),
        check.names = FALSE,
        row.names = Get(.,"levelName"))}
  }
```
