### ISSUE TITLE
calculate conditional probabilities & value of information

### ISSUE THREAD

**Issue by vnijs** [gluc/data.tree#21]
One thing I would love to add to the data.tree feature in Radiant is the ability to calculate (conditional) terminal probabilities when they are dependent on, e.g., some type of test or research. You can do the calculations beforehand and then plug-in the correct probabilities of course but a general solution strategy would be really valuable. Have you perhaps seen examples of algorithms (in R) that do this? For an example of that I'm talking about see: http://petrowiki.org/Decision_tree_analysis

**Comment by gluc** [comment]
The part you are interested in is the Bayesian stuff, right?

**Comment by vnijs** [comment]
Correct. It is not hard to calculate for a specific situation. However, I'm wondering if any more general approaches / algorithm exist.

**Comment by vnijs** [comment]
The approach mentioned in #26 also allows the calculation of conditional probabilities and the value of information ... although perhaps not as easily as my students might like :)
