### ISSUE TITLE
issue with Clone - cannot set id

### ISSUE THREAD

**Issue by vnijs** [gluc/data.tree#22]
I updated to the latest version on github. Unfortunately this broke plotting. After a looong time trying to figure out what was going on it seems that there may be an issue in the Clone function. For some reason I am not able to set an `id` for the clone. See example below. 

```r
yl <- yaml::yaml.load_file("~/Dropbox/teaching/MGT403-2015/data.tree/jennylind.yaml")
jli <- as.Node(yl)
jl <- Clone(jli)
jl$Set(id = paste0("id", 1:jl$totalCount))
t <- Traverse(jl, traversal = "level", filterFun = isNotRoot)
t[[1]]$parent$id
> NULL

jl <- jli
jl$Set(id = paste0("id", 1:jl$totalCount))
t <- Traverse(jl, traversal = "level", filterFun = isNotRoot)
t[[1]]$parent$id
[1] "id1"
```

**Comment by gluc** [comment]
Sorry about this and thx for the bug report. Yes, I replaced the clone with the new R6 method, which is much faster. If you are not using formatters (c.f. SetFormat), you can use node$clone() as a workaround until I fixed it.

**Comment by gluc** [comment]
Argh, there were quite a few things wrong with the new Clone method. Well, unit tests should not prevent us from paying attention to the details :-(
Anyway, I reverted back to the old Clone. Thanks again for letting me know quickly. Will push in a minute...

**Comment by vnijs** [comment]
Thanks @gluc !
