### ISSUE TITLE
version bump?

### ISSUE THREAD

**Issue by vnijs** [gluc/data.tree#23]
Would you mind updating the version number on github? e.g., to 0.1.7.1 or something like that? Until the new version of data.tree gets on CRAN i'm hosting a version of the package on github and users won't get the latest version if the version number stays at 1.7. Thanks @gluc

**Comment by gluc** [comment]
Sure.
I created a new release v0.1.7
However, I'm not sure I understand your point about 1.7, as this didn't exist before. So let me know if I misunderstood something.
Also note that I'm starting to professionalise my branching methodology. So from now on I'll only push hotfixes and new releases to master, and each change on master will get a new release number. For development, there's a separate dev branch.

**Comment by vnijs** [comment]
I use a github repo as a [minicran](https://github.com/RevolutionAnalytics/miniCRAN) for my students (see https://github.com/vnijs/radiant_miniCRAN). They install and update from that repo so I know they always have the same package versions I do. If the version number doesn't change but the code for data.tree does they wouldn't get the updated version when they update radiant for example. I have data.tree 1.7 packaged at the repo linked above but a bunch of stuff has changed in the code without a change to the version number. If you could make the release 1.8 or (1.7.1 or something) that would help me a lot already. If I do need something from the dev version it would be very useful if version numbers there also increment. For example, Radiant is on version 0.2.80. Rstudio's DT package in Github is on 0.1.32. Something like that would be great. Thanks @gluc

**Comment by gluc** [comment]
Ok, got it. I just published v0.1.8, though pls note that in there the Node$depth is now called Node$height.
I also fixed the Clone issue I had, so please do let me know immediately if you have problems.
In general, I'm following git flow now, so any new commit to the master will be a new release. What I'll commit to dev is not in a state yet to be used by students anyway, so no new version number there ;-)

**Comment by vnijs** [comment]
Thanks! One note, the DESCRIPTION file also needs to be updated to 1.8 for this to work. Otherwise it is still listed as 1.7. The latest pull from github (master) gives.

> packageVersion('data.tree')
[1] ‘0.1.7’

**Comment by gluc** [comment]
Argh ... thx for this. Want to stick to semver, so I created a new 0.1.9, with only the version number changed.

**Comment by vnijs** [comment]
Thanks @gluc!
