### ISSUE TITLE
`Get` and `GetAttribute` should support vectors and matrices

### ISSUE THREAD

**Issue by nacnudus** [gluc/data.tree#29]
Is this intended?

```r
data(acme)
acme$matrix <- diag(2)
GetAttribute(acme$root, "matrix") 

#      Acme Inc.
# [1,]         1
# [2,]         0
# [3,]         0
# [4,]         1
```

**Comment by gluc** [comment]
Thx for this, that is certainly not intended. Let's say, for now it is not supported ;-)

As of now, Get (and thus GetAttribute) only supports single values. However, you can always access a vector or matrix in a node directly, e.g. in your example `acme$matrix`.

Of course support for matrices and vectors is highly desirable, so I hijack your bug report and turn it into a feature request, if that's ok.

**Comment by nacnudus** [comment]
Thanks, that was fast!
