### ISSUE TITLE
Edge attributes

### ISSUE THREAD

**Issue by instantkaffee** [gluc/data.tree#3]
I understand, currently the package allows to provide attributes on node level.
I propose same per edge, I mean node-to-node relation.

Application:
1. Setup of a bill- of-materials network. Each assembled product and its component are a node each
2. The edges between the nodes has the attribute "share" a number between 0...1, representing the amound of component going into the assembled product.
3. Do calculatations based on nodes and edge attributes.

**Comment by gluc** [comment]
Interesting application!
Why not store it as an attribute of the child? e.g. 
```R
component1$ContributionToParent <- 0.2
component2$ContributionToParent <- 0.8
```
This would spare you additional methods to distinguish child nodes and edges. If you provide me with some info on the types of calculations you'd like to do, I can share some code samples.

**Comment by instantkaffee** [comment]
Because you might have more edges going out of the child to different parents.

**Comment by gluc** [comment]
Ok, I get it now. To model this, you would need a network / graph. data.tree offers an infrastructure for strictly hierarchical data, aka tree.
