### ISSUE TITLE
strange errors when using data.tree multiple times

### ISSUE THREAD

**Issue by vnijs** [gluc/data.tree#30]
Hi @gluc, 

I'm getting strange errors running data.tree (2.1) and had a hard time creating a reproducible example. Finally came up with the example below. The first time dtree is called all is fine. The second time however the same commands throws an error:

"Error in fun(node, ...) :   (list) object cannot be coerced to type 'integer'"

Other times I might get errors in the line "x$decision <- names(po[po == x$payoff])" stating that "comparison of the type are not ..."

Can you take a look? I'm trying to put my teaching notes together and can't run more than one example at a time which cuts down efficiency quite a bit :)

I tried different version of data.tree and R6 but get the same result.

Thanks

```{r}
library(data.tree)

yl_str <- "name: Newtowne Art Gallery
type: chance
High - Bidder 1:
    p: 0.5
    type: decision
    Accept - Bidder 1:
        payoff: 3000000
    Reject - Bidder 1:
    		payoff: 2000000
Low - Bidder 1:
    p: 0.5
    type: decision
    Accept - Bidder 1:
        payoff: 2000000
    Reject - Bidder 1:
    		payoff: 2000000
"

cat(yl_str, file="~/test.yaml")

dtree <- function(yl) {

  ## convert list to node object
  jl <- as.Node(yl)

  ## if type not set and isLeaf set to terminal
  pt <- function(x) if (is.null(x$type)) x$Set(type = "terminal")
  jl$Do(pt, filterFun = isLeaf)

  ## see issue https://github.com/gluc/data.tree/issues/22
  jl_init <- Clone(jl)

  ## calculate payoff
  calc_payoff <- function(x) {
    if (x$type == 'chance') x$payoff <- Aggregate(x, function(node) node$payoff * node$p, sum)
    else if (x$type == 'decision') x$payoff <- Aggregate(x, "payoff", max)

    ## subtract cost if specified
    if (!is.null(x$cost)) x$payoff <- x$payoff - x$cost
  }

  jl$Do(calc_payoff, traversal = "post-order", filterFun = isNotLeaf)

  decision <- function(x) {
    po <- sapply(x$children, function(child) child$payoff)
    x$decision <- names(po[po == x$payoff])
  }

  jl$Do(decision, filterFun = function(x) !is.null(x$type) && x$type == 'decision')

  list(jl_init = jl_init, jl = jl)
}

yl <- yaml::yaml.load_file("~/test.yaml")
result <- dtree(yl)

yl2 <- yaml::yaml.load_file("~/test.yaml")
result <- dtree(yl)
```

**Comment by gluc** [comment]
At first sight, it looks like something goes wrong in the calc_payoff. Not sure why it works the first time, though. I'll look into it in more detail, but for now I think you can fix it by replacing your calc_payoff function with this:

```{r}
  calc_payoff <- function(x) {
    if (x$type == 'chance') x$payoff <- sum(sapply(x$children, function(node) node$payoff * node$p))
    else if (x$type == 'decision') x$payoff <- max(sapply(x$children, function(node) node$payoff))
    
    ## subtract cost if specified
    if (!is.null(x$cost)) x$payoff <- x$payoff - x$cost
  }
```

I replaced `Aggregate`, which is a complex beast, as it uses recursion on children. But here you don't need that, as you are traversing the tree explicitly yourself in the following line using `Do`. 
Let me know if that doesn't work.

**Comment by vnijs** [comment]
Seems to work. Thanks @gluc!

**Comment by vnijs** [comment]
Just checking. Does the code example work now with your development version?

**Comment by gluc** [comment]
grrr ... no, just read your last comment and thought I had forgotten to close it. Sorry about that.

**Comment by gluc** [comment]
This was a really nasty bug, it's now fixed for good. Thanks for insisting. In any case, I do recommend using my suggested payoff function, without the Aggregate.
