### ISSUE TITLE
acme$ToList "attempt to apply non-function"

### ISSUE THREAD

**Issue by SixiangHu** [gluc/data.tree#35]
When convert he `acme` to list by `acme$ToList`, I've got the error message of "Error: attempt to apply non-function".

I know that I can use `as.list(acme)`, but this alternative doesn't give a "children" entry for all the leaves under it.

**Comment by gluc** [comment]
There is no function Node$ToList. There are two specialised functions, namely ToListSimple and ToListExplicit.
Type ?as.list.Node

Examples from there:

``` R
data(acme)

ToListSimple(acme, "p", "cost")

ToListExplicit(acme, "cost")
ToListExplicit(acme, "cost", unname = TRUE)
ToListExplicit(acme, "cost", unname = TRUE, nameName = "id", childrenName = "descendants")
```
