### ISSUE TITLE
Adding numbers to each node in data.tree

### ISSUE THREAD

**Issue by abrh** [gluc/data.tree#36]
I have the following tree:

 library (data.tree) 
    data (acme)
    t1<-acme
    > acme
                              levelName
    1  Acme Inc.                       
    2   ¦--Accounting                  
    3   ¦   ¦--New Software            
    4   ¦   °--New Accounting Standards
    5   ¦--Research                    
    6   ¦   ¦--New Product Line        
    7   ¦   °--New Labs                
    8   °--IT                          
    9       ¦--Outsource               
    10      ¦--Go agile                
    11      °--Switch to R 

I would like to enumerate the tree nodes name by adding the number of line to each node name as followed:

> t1
                          levelName
1  Acme Inc._1                       
2   ¦--Accounting_2
3   ¦   ¦--New Software_3
4   ¦   °--New Accounting Standards_4
5   ¦--Research_5                    
6   ¦   ¦--New Product Line_6        
7   ¦   °--New Labs_7      
8   °--IT_8                          
9       ¦--Outsource_9              
10      ¦--Go agile_10             
11      °--Switch to R_11

**Comment by gluc** [comment]
There are many different ways to achieve this. For example: 

``` R
acme$Set(id = 1:acme$totalCount)
acme$Do(function(node) node$name <- paste(node$name, node$id, sep = "_"))
```
