### ISSUE TITLE
replace old mermaid code with grViz

### ISSUE THREAD

**Issue by gluc** [gluc/data.tree#37]

**Comment by gluc** [comment]
Done in v0.3.0

**Comment by vnijs** [comment]
Interesting. Thanks for putting this in @gluc! Have you tried putting labels on the graph edges? My impression was that something like the example linked below (see bottom of thread) would be difficult or 'ugly' with grViz. Is that your experience as well?

https://github.com/rich-iannone/DiagrammeR/pull/160
