### ISSUE TITLE
best method for converting to JSON or XML

### ISSUE THREAD

**Issue by timelyportfolio** [gluc/data.tree#4]
I love the concept of `data.tree` and am intrigued by the `R6` choice.  I have been playing a little.  I tried to think through how best to convert a `data.tree` to `JSON` or `XML`, but I have not yet had any good insight.  Do you think a method for `data.tree` conversion to text would be worthwhile?

**Comment by gluc** [comment]
Regarding R6: I started with reference classes first, but ran into problems when building subclasses for my applications. R6  has been working really great.

Regarding JSON / XML: that's a natural application. My go at it would be to convert a tree to list of lists. Once you have that you can use one of the existing libraries for it. 

It's already possible now with the Get method if you're ready to take a few extra steps:

```R
library(data.tree)

#create an example tree
contacts <- Node$new("contacts")
contacts$type <- "root"
jack <- contacts$AddChild("c1")
jack$fullName <- "Jack Miller"
jack$isGoodCustomer <- TRUE
jack$type <- "customer"
jill <- contacts$AddChild("c2")
jill$fullName <- "Jill Hampsted"
jill$isGoodCustomer <- FALSE
jill$type <- "customer"
o1 <- jill$AddChild("o1")
o1$type <- "order"
o1$item <- "Shoes"
o1$amount <- 29.95

#This method converts the Node objects to environments
EnvConverter <- function(node) {
  #We take env and not list, because list has value semantics (just try it with list!)
  me <- new.env()
  if (node$type == "customer") {
    #here you decide which fields you'll want in the JSON
    #you could also format, transform, etc.
    me$fullName <- node$fullName
    me$isGoodCustomer <- node$isGoodCustomer
  } else if (node$type == "order") {
    me$item <- node$item
    me$amount <- node$amount
  } else {
    me$name <- node$name
  }
  
  if (!node$isRoot) {
    node$parent$json[[node$name]] <- me
  }
  node$json <- me
  #dummy return (not needed)
  return (node$name)
}

#iterate through the tree and call EnvConverter
contacts$Get(EnvConverter)

#needed to convert the above created environment to a list
ConvertNestedEnvironmentToList <- function(env) {
  out <- as.list(env)
  lapply(out, function(x) if (is.environment(x)) ConvertNestedEnvironmentToList(x) else x)
}

mylist <- ConvertNestedEnvironmentToList(contacts$json)

library(rjson)

#convert the list to a JSON, using the package of your choice
toJSON(mylist)

```

Hope that helps!

**Comment by timelyportfolio** [comment]
Definitely helps a lot, and I really appreciate both the package and your response.  Makes sense now.  I'll play to see what I can make happen.  Not sure if you saw this little unrelated [data.tree gist experiment](https://gist.github.com/timelyportfolio/3d82ac671c58de5117fe).
