### ISSUE TITLE
Allow adding siblings

### ISSUE THREAD

**Issue by gluc** [gluc/data.tree#41]
Add just after the sibling

**Comment by gluc** [comment]
You can already do node$parent$AddChild("name"), but that will always add it as last child.

**Comment by gluc** [comment]
`node$AddSibling("name")`

**Comment by glennmschultz** [comment]
Thanks, I tied to add a sibling and got the following when I used AddSibling Error: attempt to apply non-function.  I am doing something wrong here.  I tried the alternative A_Child$AddSibling and the same error was returned

MyTree <- Node$new("MyTree")
A_Child <- MyTree$AddChild("A_Child")
A_Sibling <- MyTree$AddSibling("A_Sibling")

print(MyTree)

**Comment by gluc** [comment]
This is only working on the dev branch, and not yet released to master or CRAN. Sorry about that, it wasn't clear. You can do:
```r
devtools::install_github("gluc/data.tree", ref = "dev")
```
