### ISSUE TITLE
Add print method

### ISSUE THREAD

**Issue by artemklevtsov** [gluc/data.tree#42]
Hi.

It would be useful to add print method as described in the R6 docs: https://cran.r-project.org/web/packages/R6/vignettes/Introduction.html#printing-r6-objects-to-the-screen.

It helpful to use the `Node` objects across packages.

S3 print method may be a wrapper:

```r
print.Node <- function(...) {
    if (is.function(x$print)) {
        x$print(...)
    } else {
        # something else
    }
}
```

**Comment by gluc** [comment]
Not sure I'm getting the full picture. data.tree already defines a print.Node method, using standard R generics. E.g. the following are all equivalent:

```r
data(acme)
acme
print(acme)
data.tree:::print.Node(acme)
```
I think you should be able to use it from another package as well. 
You can still use the R6 default print method, like so:
```r
R6:::print.R6(acme)
```
Originally, the print method was sitting on the R6 object, as described at the above link. However, I'm trying to limit the number of elements (methods, actives) on the R6 object, as storage size of serialized R6 increases a lot with each additional element.
Or maybe I misunderstood. If so, pls explain me the exact use case. Thanks!

**Comment by artemklevtsov** [comment]
I don't use non exported functions through `:::` (CRAN policies). And `print.Node` will works only when `data.tree` is loaded.

**Comment by gluc** [comment]
Are you sure the data.tree print generic is not being called? I do the following, on a brand new R session:

```r
rm(list=ls())
library(ahp)
ahpFile <- system.file("extdata", "car.ahp", package="ahp")
carAhp <- Load(ahpFile)
print(carAhp)
```

And then I get:

```
                    levelName
1  Buy Car                   
2   ¦--Cost                  
3   ¦   ¦--Purchase Price    
4   ¦   ¦   ¦--Accord Sedan  
5   ¦   ¦   ¦--Accord Hybrid 
etc.
```

**Comment by artemklevtsov** [comment]
Hm. Seems you're right. My problem is to change default print options for the `Node` class. I need print some addition attributes without explicit calls.

**Comment by gluc** [comment]
You can always subclass Node and write your own implementation of print. There are two ways to do it:
1. simple: use the standard R mechanism, i.e. add a string to the class attribute, and then write a generic method, e.g. print.MySubclassOfNode
2. proper: use R6 subclassing mechanism, and then e.g. define a print method directly in your subclass.
If you give me more details, I might be able to help.
