### ISSUE TITLE
"Clone" problem

### ISSUE THREAD

**Issue by wuandtan** [gluc/data.tree#44]
I encounter the problem of function "Clone". In some cases, "Clone" does not clone the original data.tree. See the following example.

Case 1 (does not work!!):

library(data.tree)
library(ape)
data(bird.families)
bf <- as.Node(bird.families)
bfnew <- Clone(bf)
bfnew

Error in node$children[keep] : invalid subscript type 'list'

case 2 (works!!):
library(datasets)
data(acme)
acmeClone <- Clone(acme)
acmeClone

1  Acme Inc.                       
2   ¦--Accounting                  
3   ¦   ¦--New Software            
4   ¦   °--New Accounting Standards
5   ¦--Research                    
6   ¦   ¦--New Product Line        
7   ¦   °--New Labs                
8   °--IT                          
9       ¦--Outsource               
10      ¦--Go agile                
11      °--Switch to R

**Comment by gluc** [comment]
Thanks for the report. This should be fixed in dev.

**Comment by wamserma** [comment]
Please also check Prune(), where I have the same issue with current master (0.2.4 CRAN).

**Comment by gluc** [comment]
I will check, but I'm pretty sure that's also solved with the same fix.

**Comment by gluc** [comment]
This is fixed in the next release. As a temporary workaround, you can override the Clone() method with this:

```r
Clone <- function(node, pruneFun = NULL, attributes = FALSE) {
  ClonePrivate(node, pruneFun, attributes)
}



ClonePrivate <- function(node, pruneFun = NULL, attributes = FALSE, firstCall = TRUE) {

  myclone <- node$clone()
  if (attributes) attributes(myclone) <- attributes(node)
  if (!is.null(pruneFun) && length(node$children) > 0) {
    keep <- sapply(node$children, pruneFun)
    children <- node$children[keep]
    rm(list = names(node$children)[!keep], envir = myclone)
  } else children <- node$children
  myclone$children <- lapply(children, function(x) ClonePrivate(x, pruneFun, attributes, firstCall = FALSE))
  for (child in myclone$children) {
    myclone[[child$name]] <- child
    child$parent <- myclone
  }
  if (length(myclone$children) == 0) myclone$children <- NULL
  if (firstCall) myclone$parent <- NULL #myclone$RemoveAttribute("parent", stopIfNotAvailable = FALSE)
  return (myclone)
}

```
