### ISSUE TITLE
Cloning subtrees retains reference to (old) parent

### ISSUE THREAD

**Issue by wamserma** [gluc/data.tree#49]
This is best explained with an example:

```r
require(data.tree)
data(acme)
subClone <- Clone(Climb(acme,"IT"))
print(subClone)
print(acme)
print(subClone$parent)
print(subClone$root)

# this should not affect acme
subClone$name <- "banana"
print(acme)

# however, climbing works 
Climb(acme,"IT")
Climb(acme,"banana")
```

It seems the Clone is not fully detached from the original tree, especially the parent attributes of the new root node are still pointing into the old tree.

**Comment by wamserma** [comment]
Probably adding 
```r
myclone$parent <- NULL
```
after https://github.com/gluc/data.tree/blob/dev/R/node_methods.R#L154 is enough.

**Comment by gluc** [comment]
Thanks! Fixed it ... and documentation as well. Will be closed when dev is merged into master.
