### ISSUE TITLE
Add Find() function

### ISSUE THREAD

**Issue by wamserma** [gluc/data.tree#52]
Having a function to `Find()` a node by ID would be very convenient.

A quick implementation could be

```r
Find <- function(node, name, traversal = c("pre-order", "post-order", "in-order", "level",
                                     "ancestor"), all = F){

  ret <- Traverse(node, traversal, pruneFun = NULL, filterFun = function(x) {x$name == name})
  if (!all) ret <- ret[[1]]
  return(ret)

}
```
but for performance it would be nice if `Traverse()` returned after the first hit, when `all=F`.

**Comment by wamserma** [comment]
Node that the above fails in two ways, when `name` is not in the tree: First due to https://github.com/gluc/data.tree/issues/51 and second because `ret[[1]]` might be out of bounds then. A workaround implementation could be 
```r
Find <- function(node, name, traversal = c("pre-order", "post-order", "in-order", "level",
                                     "ancestor"), all = F){

  trav <- Traverse(node, traversal, pruneFun = NULL, filterFun = NULL)
  ret <- trav[sapply(trav,function(x) x$name == name)]

  if (length(ret) == 0) return(vector("list",0))
  if (!all) return(ret[[1]])
  return(ret)

```

**Comment by gluc** [comment]
Agree that `Find` could be a convenient shortcut, but then I would suggest allowing finding by multiple fields, applying AND logic. Along the lines of:

```r
Find(node, name = "myname")
#find first node whose name is "myname" and which are not a leaf:
root$Find(node, name = "myname", isLeaf = FALSE)
```
(Note that name does not have to be unique in the tree, only among siblings.)

How about omitting the `all` parameter, and asking the user to always use `Traverse` in case he wants `all = TRUE`?

Your implementation is fine, but if I do this, I'd probably want to implement it such that it stops after the first find.

**Comment by wamserma** [comment]
My implementation was just quick example. If you search over the same tree multiple times, you definitely should create a traversion and search on that. So maybe Find() could be implemented as a pair of functions or also accept an existing traversion.

**Comment by wamserma** [comment]
I played around a bit more with repeatedly looking up nodes by name from the same tree. Testcase was a tree with ~10k nodes with unique names. I compared lookup via hashtable (from package `hash`) with lookup via binary search on a sorted list of names.

Preparation:
1. use Traverse() to get a list and name the list
```r
trav <- Traverse(tree, "level", pruneFun = NULL, filterFun = NULL)
names(trav) <- sapply(trav,function(x) x$name)
```

2. Create a Name -> Node Hashtable and a sorted list 

```r
# create hashtable
ht <- hash(trav)

# sort by names
ord <- order(names(trav))
trav.sorted<-trav[ord]
```

Test: I looked up each name once in random order (the random order was determined before the benchmark was launched).
Hashtable-Lookup was simply done with [[]] and binary search was done none-recursive with integer indices (in pure R). It seems that the string comparisons slow down the binary search a bit. Averaged on 100 runs the runtime of the binary search was 5x that of the hashtable lookups. Using compiler::compile improved things a bit for the binary search (hashtable was the same) to 2.5x the runtime of hashtable. The implementation suggested above requires more than 5000x as long for the 10k lookups, so if one has more than a few lookups on the same tree the preparation of the hash table should definitely pay off. This should at least be mentioned in the documentation of a future Find() function.

**Comment by gluc** [comment]
Ok, thx. I think I got it now:
1. you're mainly interested in the performance of the suggested Find() function
2. you're only interested in finding by name

If that's the case, then I suggest to have the signature as follows:
```r
Find <- function(node, name)
```
Because
a.) the Find function is mainly useful if node name's are unique within the entire tree -> no all needed, the first found is always returned
b.) the implementation might try to be smart or faster (e.g. hash, e.g. parallel, etc.) if traversal is not important.

Agree?

Additionally: if you think this is a frequent use case, then we might discuss an additional parameter on the constructor, e.g.

```r
Node$new("myname", hash = TRUE)
```

Though I would prefer using environments (to avoid another dependency).

What do you think?

**Comment by wamserma** [comment]
Yes, that's pretty much what I thought of. But the hash parameter on the constructor is a bit ambiguous. This might lead to scenarios where only part of the tree is captured in the environment.

It would be better to show in the documentation that for repeated lookups one should get a desired traversal, store the results in a named list/environment/hash table and then use the lookup functions provided by these structures. As this can be done with two or three lines of R I don't think another convenience function is needed, as long as an example in given in a prominent place (doc, vignette)-
