### ISSUE TITLE
Auto name

### ISSUE THREAD

**Issue by gluc** [gluc/data.tree#54]
For some cases, no natural id/name exists when converting e.g. a list of lists to data.tree. Currently, the user has to create an artificial id so the FromListExplicit method can separate the nodes. It would be useful if the conversion allowed to attribute automatically synthetic names. 
See http://stackoverflow.com/questions/35278342/recursively-assign-unique-names-to-nodes-in-a-data-tree-object for details.
Or http://stackoverflow.com/questions/35444968/read-json-file-into-a-data-frame-without-nested-lists

**Comment by dylanbeaudette** [comment]
Here are a couple of options for iteratively re-naming the elements of a list.

`# serial number added to names
makeNamesUnique <- function(l) {
  l.names <- names(l$Children)
  # multiple children types
  tab <- table(l.names)
  t.names <- names(tab)
  
  # iterate over types
  for(this.type in seq_along(t.names)) {
    # iterate over duplicate names
    # get an index to this type
    idx <- which(l.names == t.names[this.type])
    for(this.element in seq_along(idx)) {
      # make a copy of this chunk of the tree
      l.sub <- l$Children[[idx[this.element]]]
      # if this is a terminal leaf then re-name and continue
      if(is.null(l.sub$Children)) {
        # print('leaf')
        names(l$Children)[idx[this.element]] <- paste0(t.names[this.type], '_', this.element)
      }
      # otherwise re-name and then step into this element and apply this function recursively
      else {
        # print('branch')
        names(l$Children)[idx[this.element]] <- paste0(t.names[this.type], '_', this.element)
        # fix this branch and splice back into tree
        l$Children[[idx[this.element]]] <- makeNamesUnique(l.sub)
      }
    }
  }

  return(l)
}

# use hash function for unique names
makeNamesUnique2 <- function(l) {
  
  # iterate over list elements
  for(i in seq_along(l$Children)) {
    # get curret name
    i.name <- names(l$Children)[i]
    # get the contents
    i.contents <- l$Children[[i]]
    # make a new name via digest
    i.name.new <- paste0(i.name, '_', digest(i.contents, algo = 'xxhash32'))
    
    # if this is a terminal leaf then re-name and continue
    if(is.null(i.contents$Children)) {
      # print('leaf')
      names(l$Children)[i] <- i.name.new
    }
    # otherwise re-name and then step into this element and apply this function recursively
    else {
      # print('branch')
      names(l$Children)[i] <- i.name.new
      # fix this branch and splice back into tree
      l$Children[[i]] <- makeNamesUnique2(i.contents)
    }
  }
    
  return(l)
}`

**Comment by gluc** [comment]
Thx, but I would probably tend to just use a random name, or a running number. Once the tree has been successfully constructed, you can use whatever function/logic you want to modify the name.

**Comment by dylanbeaudette** [comment]
Good idea. Care to add to the package as an option an init time?

**Comment by gluc** [comment]
You mean as an attribute on each Node? What would you use this for?

Dylan Beaudette <notifications@github.com> schrieb am Di., 9. Feb. 2016 um
20:53 Uhr:

**Comment by dylanbeaudette** [comment]
I was thinking something along the lines of an argument at init time that would make the names unique. Kind of like when creating a `data.frame` object, the `make.names` function is invoked.

**Comment by gluc** [comment]
@dylanbeaudette I added the mentioned auto name feature to the dev branch, so the following should now work out of the box:
```r
l <- structure(list(RuleStart = structure(list(Children = structure(list(
  RuleOperator = structure(list(Children = structure(list(RuleRule = structure(list(
    Children = NULL, RefId = "49446"), .Names = c("Children", 
                                                  "RefId")), RuleRule = structure(list(Children = NULL, RefId = "15976"), .Names = c("Children", 
                                                                                                                                     "RefId")), RuleRule = structure(list(Children = NULL, RefId = "49444"), .Names = c("Children", 
                                                                                                                                                                                                                        "RefId")), RuleRule = structure(list(Children = NULL, RefId = "15748"), .Names = c("Children", 
                                                                                                                                                                                                                                                                                                           "RefId")), RuleRule = structure(list(Children = NULL, RefId = "49440"), .Names = c("Children", 
                                                                                                                                                                                                                                                                                                                                                                                              "RefId")), RuleRule = structure(list(Children = NULL, RefId = "15746"), .Names = c("Children", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "RefId")), RuleRule = structure(list(Children = NULL, RefId = "49449"), .Names = c("Children", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "RefId"))), .Names = c("RuleRule", "RuleRule", "RuleRule", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "RuleRule", "RuleRule", "RuleRule", "RuleRule")), Type = "product"), .Names = c("Children", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "Type"))), .Names = "RuleOperator")), .Names = "Children")), .Names = "RuleStart")

# convert XML list into data.tree object
n <- FromListExplicit(l$RuleStart, childrenName='Children')
print(n, "Type", "RefId")
```

I would appreciate some feedback. Do you think that's clear, and the documentation (`?as.list.Node`) is clear? Thx for your feedback.
