### ISSUE TITLE
Assign function to node

### ISSUE THREAD

**Issue by dylanbeaudette** [gluc/data.tree#55]
It would be very convenient to assign more than text / numbers to the attributes of a node. For example:

```r

library(data.tree)

dt <- Node$new('a new node')
dt$AddChild('first child')
dt$AddChild('second child')

f1 <- function(i) i + 1
f2 <- function(i) i + 2

dt$`first child`$AddChildNode(f1)
```

**Comment by gluc** [comment]
You **can** assign a function as a **field** of a node, e.g. like so:

```r
library(data.tree)

dt <- Node$new('a new node')
dt$AddChild('first child')
dt$AddChild('second child')

f1 <- function(i) i + 1
f2 <- function(i) i + 2

dt$`first child`$f1 <- f1
dt$`first child`$f1(3)
```

However, you can
* only assign `Node` objects as a **child** of another `Node`
* only use characters as `name` of a `Node` (or types easily convertible to character)

**Comment by dylanbeaudette** [comment]
Perfect, thank you.
