### ISSUE TITLE
An example doesn't work on R 3.1.2

### ISSUE THREAD

**Issue by talgalili** [gluc/data.tree#57]
A friend of mine got an environment error when running the following code (from your example) in R 3.1.2 on mac (it works fine on my Windows R 3.2.3):

```r
#install.packages("data.tree")
library(data.tree)

acme <- Node$new("Acme Inc.")
  accounting <- acme$AddChild("Accounting")
    software <- accounting$AddChild("New Software")
    standards <- accounting$AddChild("New Accounting Standards")
  research <- acme$AddChild("Research")
    newProductLine <- research$AddChild("New Product Line")
    newLabs <- research$AddChild("New Labs")
  it <- acme$AddChild("IT")
    outsource <- it$AddChild("Outsource")
    agile <- it$AddChild("Go agile")
    goToR <- it$AddChild("Switch to R")

print(acme)
plot(acme)


SetGraphStyle(acme, rankdir = "TB")
SetEdgeStyle(acme, arrowhead = "vee", color = "grey35", penwidth = 2)
SetNodeStyle(acme, style = "filled,rounded", shape = "box", fillcolor = "GreenYellow", 
            fontname = "helvetica", tooltip = GetDefaultTooltip)
SetNodeStyle(acme$IT, fillcolor = "LightBlue", penwidth = "5px")
plot(acme)


```

With regards,
Tal

**Comment by gluc** [comment]
I just checked on Windows with 3.1.2, and there it works. I don't have a Mac, so I can't check. But what I noted is that on [CRAN](https://cran.r-project.org/web/packages/data.tree/index.html), the r-oldrel binary for OS X is data.tree version 0.1.6, i.e. a very old version. 
So, two things:
1. could you pls check with sessionInfo() what version of the data.tree package you have?
2. Do you know how this works with CRAN? Who builds the OS X binaries? And is it normal that they don't build it for r-oldrel?

**Comment by talgalili** [comment]
As said, it was on a friend's computer. She had version 0.3.0.
If you can't reproduce it, then you can let it be (she solved it by upgrading R).
But I thought you'd like to know. (maybe something else caused it - but I suspect it has to do with the R version)

**Comment by gluc** [comment]
Ok, thx. I close it for now, but I'll investigate more if I get similar feedback from someone else.
