### ISSUE TITLE
allow converting a data.tree to and from a party class from partykit

### ISSUE THREAD

**Issue by gluc** [gluc/data.tree#6]
as discussed with Achim Zeileis
see http://cran.r-project.org/web/packages/partykit/vignettes/partykit.pdf

**Comment by vnijs** [comment]
What about the other-way around (i.e., party to data.tree)?

**Comment by gluc** [comment]
Indeed, that's what I meant. Changed the title.

**Comment by vnijs** [comment]
Nice! Is there something similar for output from rpart perhaps? I'm interested if these these new functions in data.tree would make it easier to use Diagrammer / Mermaid to visualize trees from partykit / rpart

**Comment by gluc** [comment]
Not directly for now, but you can use the detour via partykit:

```{r}
fit <- rpart(Kyphosis ~ Age + Number + Start, data = kyphosis)
prty <- as.party(fit)
tree <- as.Node(prty)
print(tree, 
       "splitname",
       count = function(node) nrow(node$data), 
       "splitLevel")
```
Yes, you can plot this. E.g.:

```{r}
 SetNodeStyle(tree, 
              label = function(node) paste0(node$name, ": ", node$splitname), 
              tooltip = function(node) paste0(nrow(node$data), " observations"),
              fontname = "helvetica")
 
SetEdgeStyle(tree,
             arrowhead = "none",
             label = function(node) node$splitLevel,
             fontname = "helvetica",
             penwidth = function(node) 12 * nrow(node$data)/nrow(node$root$data),
             )
 
 plot(tree)
```

**Comment by gluc** [comment]
Implemented conversion from party -> data.tree (c.f. `as.Node.party`). data.tree -> party will not be implemented for now, as it would require a very specific structure.

**Comment by timelyportfolio** [comment]
And a very basic use with `networkD3`.

```
library(networkD3)
networkD3::diagonalNetwork(ToListExplicit(tree, unname=TRUE, childrenName="children"))
```
