### ISSUE TITLE
Unnamed objects in list are lost

### ISSUE THREAD

**Issue by noamross** [gluc/data.tree#61]
When a list contains non-list objects without names, they are lost, as in the following:

```
> a = list(a=1,2, list(c=2))
> b  =as.Node(a)
> b
  levelName
1     Root 
2      °--1
> b$fields
[1] "a"
```

As you can see, the first object, `a`, is captured, and the third object, an unnamed list, is also captured, but the unnamed object, `2`, disappears.  These fields should be captured and named.  I'll see what I can do. Should their names be numbers, as with unnamed list objects?  Or some other designation, `.1`, `.2`, perhaps?

**Comment by gluc** [comment]
I get your point. Currently, only named list elements are considered, except if mode = "simple", then lists are interpreted to contain children and the as.Node auto-assigns a name. 
Not sure how much sense un-named Node fields make. Nodes are environments, and as such their members are not ordered. If you auto-assign a name (similar to children), then the user has a hard time figuring out which value represents what.

**Comment by noamross** [comment]
I see.  My use case is dealing with a large, heterogenous tree imported via JSON.  Within the JSON there are unnamed arrays, so the elements of those arrays, whether simplified via `jsonlite::fromJSON(...,simplifyVector)` or not, are unnamed atomic types in list.  So when I convert this list to `data.tree` there are always going to be unnamed values that I need to retrieve, and suspect there is plenty of JSON out there with similar structures.

Giving the unnamed fields numeric numbers helps somewhat: it provides the information that was previously stored in ordering of the array.  I also like this because, when going back from `data.tree` to lists or JSON, I can remove names of both children and fields by looking for numbers.
