### ISSUE TITLE
data.frame to data.tree

### ISSUE THREAD

**Issue by jto888** [gluc/data.tree#68]
In my jto888/FaultTree project the hierarchy tree data is assembled in a dataframe. Each row represents a node. Each node has a uniquely assigned ID represented in a column with that name. Nesting is indicated by a Parent column listing the ID of the parent node. (A negative value is used for the root parent,alternatively)
I understand that this is common representation, and have seen tutorials in the .Net world for building the nested json from such a flat file. 
However, reading through the data.tree documentation it is not clear to me how such a flat file would be converted to data.tree.

**Comment by gluc** [comment]
@jto888 Yes, it looks like your packages could benefit a great deal from data.tree as an underlying data structure.

Regarding your question: Pls have a look at `?as.Node.data.frame`. Specifically, you might be interested in `FromDataFrameNetwork`. I'm not 100% sure given your description, but something like that might be what you are looking for:

```{R}
#data frame
from <- c(-1, 1, 2, 3, 3, 2)
to <- c(1, 2, 3, 4, 5, 6)
nme <- letters[to]
df <- data.frame(from, to, nme, stringsAsFactors = FALSE)

#convert to data.tree structure
tr <- FromDataFrameNetwork(df)

#-1 is created as root, so let's remove it:
tr <- Clone(tr$children[[1]])

print(tr, "nme")
```

This gives:

```
      levelName nme
1 1               a
2  °--2           b
3      ¦--3       c
4      ¦   ¦--4   d
5      ¦   °--5   e
6      °--6       f
```

**Comment by jto888** [comment]
Yes, Christoph, this looks like what I was after. I will work on this 
and notify you of success.
