### ISSUE TITLE
as.node does not perform well for large data sets

### ISSUE THREAD

**Issue by kickbox** [gluc/data.tree#73]
Takes more time to generate nodes through as.node from a data.frame. Need to optimise for performance.

**Comment by gluc** [comment]
@kickbox Happy to look into this, but you need to be more specific. Do you mean it takes more time compared to a previous version? That would be surprising. Or do you mean it's just generally slow?
Pls provide a reproducible example and some performance stats, as well as the time you would consider acceptable.
In any case, note that data.tree hasn't been designed for large data sets.

**Comment by kickbox** [comment]
Hello @gluc, sorry for the missing information. I have attached my data set too now. [MyData2.zip](https://github.com/gluc/data.tree/files/358632/MyData2.zip)

There was an improvement over the previous version ofcourse. But I think there is still scope for performance improvement as "as.node" takes 19 seconds and "ToDataFrameTree" takes 49 seconds with the attached data set. 

My guess is that when there are columns with strings with more characters, the performance decreases.

```
df <- read.csv("C:/Users/emmanuel/Documents/MyData2.csv")
df$absDiff <- abs(qd$diff)
df$value <- qd$absDiff

df$pathString <- paste("Root" ,df$Costcenter, df$Vendor, df$V3,   sep = "/")

st <- Sys.time()
s <- as.Node(df ,mode="table")
en <- Sys.time()
print(paste("as.Node time taken(sec):",en-st))


s$Do(function(node) node$value <- Aggregate(node , attribute = "value", aggFun = sum), traversal = "post-order")
s$Set(id = 1:s$totalCount)
$Set(parent1 = c(function(self) GetAttribute(self$parent, "id", format = identity)))

#copy the data tree structure to a data.frame
st <- Sys.time()
test <- ToDataFrameTree(s,"value", "level", "id","parent1")
en <- Sys.time()
print(paste("ToDataFrameTree time taken(sec):",en-st))
```
My system details 
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```
```
CPU: i5 4300U @1.9GHz 2.5GHz
Ram: 16GB
SSD: 256 GB
```

**Comment by gluc** [comment]
Can you please test with the latest version published to CRAN? Thx.

**Comment by gluc** [comment]
Closing, as this does not seem to be an issue anymore.
