### ISSUE TITLE
Plotting does nothing

### ISSUE THREAD

**Issue by arendsee** [gluc/data.tree#75]
The plot function silently does nothing on my system.

Here is my sample code (copied from the vignette):

``` R
library(data.tree)

acme <- Node$new("Acme Inc.")
  accounting <- acme$AddChild("Accounting")
    software <- accounting$AddChild("New Software")
    standards <- accounting$AddChild("New Accounting Standards")
  research <- acme$AddChild("Research")
    newProductLine <- research$AddChild("New Product Line")
    newLabs <- research$AddChild("New Labs")
  it <- acme$AddChild("IT")
    outsource <- it$AddChild("Outsource")
    agile <- it$AddChild("Go agile")
    goToR <- it$AddChild("Switch to R")

plot(acme)
```

No image is produced when I run this and no error message or warning is printed. The function runs for a second and then ends silently.

I am using
 * R v3.3.1
 * data.tree v0.3.5
 * DiagrammeR v0.8.2

And `uname -a` output:

```
Linux xxx 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux
```

**Comment by gluc** [comment]
Hi, thx for the patience, this kind of slipped through my attention.
data.tree plotting uses DiagrammeR under the hood. And that uses graphvis and dot. The output generated is html. On most systems, this works fine (both from RGui, RStudio, and other IDEs). Some problems exist on some consoles, and when integrating e.g. into PDFs using knitr (see e.g. https://github.com/rich-iannone/DiagrammeR/issues/133 ).

Can you run the DiagrammeR samples, e.g. here: https://github.com/rich-iannone/DiagrammeR

**Comment by arendsee** [comment]
The problem arose while trying to compile knitr pdfs, so I think it is the same problem discussed over at DiagrammeR. 

My minimal example actually does compile to html. I had just missed it because I was expecting something in the normal R port.

Anyway, I've now got a minimal knitr document working. There were nice help messages that told me to install webshot and phanomjs.

``` R
\documentclass{article}
\begin{document}
<<>>=
  require(data.tree)
  require(webshot)
  ## to install phantomjs
  # webshot::install_phantomjs()
  acme <- Node$new("Acme Inc.")
    accounting <- acme$AddChild("Accounting")
      software <- accounting$AddChild("New Software")
      standards <- accounting$AddChild("New Accounting Standards")
    research <- acme$AddChild("Research")
      newProductLine <- research$AddChild("New Product Line")
      newLabs <- research$AddChild("New Labs")
    it <- acme$AddChild("IT")
      outsource <- it$AddChild("Outsource")
      agile <- it$AddChild("Go agile")
      goToR <- it$AddChild("Switch to R")

  plot(acme)
@
\end{document}
```

**Comment by gluc** [comment]
@arendsee Are you saying you managed to knit that to a pdf document? If you did, I would be immensely interested in the details, as I didn't get this to work as of now!

**Comment by arendsee** [comment]
@gluc, Yeah, I got it working with knitr.

Here is a zip file with my Makefile, my output pdf, and the knitr document:

[data-tree-test.zip](https://github.com/gluc/data.tree/files/459785/data-tree-test.zip)

I called sessionInfo() in the knitr document.

As far as the detailed are concerned, I didn't do anything special, besides install webshot and phantomjs (as above). Maybe this is a new feature of DiagrammeR?

**Comment by vnijs** [comment]
@gluc and @arendsee The latest version of knitr works webshot to create schreen shots of DiagrammeR plots and htmlwidgets. See attached pdf with a DiagrammeR plot and a DT table

[report (77).pdf](https://github.com/gluc/data.tree/files/459819/report.77.pdf)

**Comment by arendsee** [comment]
Thanks @vnijs, that is really cool.

**Comment by gluc** [comment]
Thanks, indeed very cool!
