### ISSUE TITLE
FromDataFrameTable() Error in `[[.default`(myrow, pathName) : subscript out of bounds

### ISSUE THREAD

**Issue by happyshows** [gluc/data.tree#77]
Hi,

Could you share a correct usage of FromDataFrameTable in the following example?

```
a <- 'HSBI_1/FT_1/HPBI_HSLT_1/HCESLT_1'
b <- 'HSBI_1/FT_2/HPBI_HSLT_1/HCESLT_1'
c <- 'HSBI_1/FT_3/HPBI_HSLT_1/HCESLT_1'
tst <- data.frame(pathString = c(a,b,c))
FromDataFrameTable(tst)
```

Error in `[[.default`(myrow, pathName) : subscript out of bounds

**Comment by gluc** [comment]
There seem to be one and a half bugs :-(
1. (half bug) pathString cannot be a factor
2. FromDataFrameTable only works of there is at least one extra column

I will look into fixing these asap. In the meantime, the following works:

```
a <- 'HSBI_1/FT_1/HPBI_HSLT_1/HCESLT_1'
b <- 'HSBI_1/FT_2/HPBI_HSLT_1/HCESLT_1'
c <- 'HSBI_1/FT_3/HPBI_HSLT_1/HCESLT_1'
tst <- data.frame(pathString = c(a,b,c), x = 1, stringsAsFactors = FALSE)
FromDataFrameTable(tst)
````

**Comment by happyshows** [comment]
@gluc can you double check it's resolved? I still see 
Error in myrow[[pathName]] : subscript out of bounds
without the 'x=1'

**Comment by gluc** [comment]
@happyshows  This has been fixed on github in the latest release. However, that's not on CRAN (we are urged to publish to CRAN only every three months or so).
The following works for me:

```
devtools::install_github("gluc/data.tree")

library(data.tree)

a <- 'HSBI_1/FT_1/HPBI_HSLT_1/HCESLT_1'
b <- 'HSBI_1/FT_2/HPBI_HSLT_1/HCESLT_1'
c <- 'HSBI_1/FT_3/HPBI_HSLT_1/HCESLT_1'
tst <- data.frame(pathString = c(a,b,c))
FromDataFrameTable(tst)
```

**Comment by happyshows** [comment]
confirmed thanks.
