### ISSUE TITLE
Conflict between variable name and field name

### ISSUE THREAD

**Issue by eaurele** [gluc/data.tree#78]
``` R
df <- data.frame(V1 = c("bar", "bar/foo"), foo = 1:2, stringsAsFactors = FALSE)
as.Node(df, pathName = "V1")
```

causes:
`Error in mynode$level : $ operator is invalid for atomic vectors`
probably because of variable `foo` named like field `foo`

**Comment by gluc** [comment]
That is indeed not possible, as both name and fields are stored in the same environment. I agree that the error message could be a bit more expressive. Also, I had the idea to make this a bit less likely to happen with #66. But I'm still undecided.

Will try to improve the error message.

**Comment by gluc** [comment]
A warning has been added if name conflict occurs.
