### ISSUE TITLE
Is there a way to create a tree from bottom-up (leafs to root)

### ISSUE THREAD

**Issue by sainathadapa** [gluc/data.tree#86]
As the title says, is there a way to create a tree starting from the leafs? In other words, can I implement agglomerative hierarchical clustering using data.tree? I saw the ID3 example in the vignette and wondered if implementing agglomerative hierarchical clustering (like hclust) is possible in a similar fashion?

**Comment by gluc** [comment]
Yes, that's of course possible. You can create a leaf programmatically using the `leaf <- Node$new(name)` instantiator. And then you can add it to a parent like this:

```
parent <- Node$new(parentName)
parent$AddChildNode(leaf)
```

**Comment by sainathadapa** [comment]
Thanks! I didn't think of that.
