### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ptoche** [gluc/data.tree#89]
Sorry to barge in, but any suggestions about this problem? 

mavericks not supported? a temporary problem with server? something else? Thanks.

        > install.packages("data.tree", repos=c("http://rstudio.org/_packages", "http://cran.rstudio.com"))
        Installing package into ‘/Users/.../R/library’
        (as ‘lib’ is unspecified)
        Warning in install.packages :
          URL 'http://rstudio.org/_packages/bin/macosx/mavericks/contrib/3.3/PACKAGES.gz': status was '404 Not Found'
        Warning in install.packages :
          URL 'http://rstudio.org/_packages/bin/macosx/mavericks/contrib/3.3/PACKAGES': status was '404 Not Found'
        Warning in install.packages :
          unable to access index for repository http://rstudio.org/_packages/bin/macosx/mavericks/contrib/3.3:
          cannot download all files
        trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/data.tree_0.7.0.tgz'
        Content type 'application/x-gzip' length 1583127 bytes (1.5 MB)
        ==================================================
        downloaded 1.5 MB

        The downloaded binary packages are in
            /var/folders/zr/27bbpbzd12b46pm87vsclt140000gp/T//RtmphCUyIA/downloaded_packages
        > library("data.tree")
        Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
          namespace ‘htmlwidgets’ 0.6 is already loaded, but >= 0.8 is required
        Error: package or namespace load failed for ‘data.tree’
        > data(GNI2010)
        Warning message:
        In data(GNI2010) : data set ‘GNI2010’ not found

**Comment by gluc** [comment]
* looks like you have an old version of htmlwidgets. As the error message says, you'll need >= v 0.8
* regarding GNI2010, I think that's from an old version of the treemap package, but not from data.tree. So the following would work:

```
library(treemap)
data(GNI2014)
```

**Comment by ptoche** [comment]
Thanks gluc! It was perhaps some sort of server issue, as the problem resolved itself today when it wouldn't before. I was trying to replicate some stuff from the demo: http://jkunst.com/r/presenting-highcharter/, but I see now that some of the code is outdated (uses GNI2010 and the deprecated hc_add_series_treemap) and there are typos (e.g. hc_add_serie instead of hc_add_series). Thanks!
