### ISSUE TITLE
Cannot plot tree

### ISSUE THREAD

**Issue by kyp0717** [gluc/data.tree#96]
When I tried to plot the tree I get the following error:

> plot(acme)
Error in do.call(create_node_df, c(n = length(tr), myargs)) : 
  object 'create_node_df' not found

**Comment by gluc** [comment]
What is the output of your `sessionInfo()`?

**Comment by kyp0717** [comment]
Issue resolved.  I perform a reboot and everything is okay.
Sorry to have posted this.
