### ISSUE TITLE
How do you reference the top node using SetNodeStyle?

### ISSUE THREAD

**Issue by kyp0717** [gluc/data.tree#97]
I am not sure if this is the right place to ask this question but here it is:
I created a tree using the R package data.tree. I would like to edit the top node only but I am not sure how to refer to it using SetNodeStyle. Here is the code:
`library(data.tree)
truven <- Node$new("truven")
  opioid <- truven$AddChild("opioid")
  iro.only <- opioid$AddChild("iro.only")
  ero.n.iro <- opioid$AddChild("ero.n.iro")
     ge.27mth <- ero.n.iro$AddChild("ge.27mth")
     l.27mth <- ero.n.iro$AddChild("l.27mth")
  ero.only <- opioid$AddChild("ero.only")

SetGraphStyle(truven, rankdir = "TB")
SetEdgeStyle(truven, arrowhead = "vee", color = "grey35", penwidth = 1)
 SetNodeStyle(truven$truven, style = "filled,rounded", shape = "box", fillcolor = "Green", 
         fontname = "helvetica", tooltip = GetDefaultTooltip)     

 plot(truven)`

Notice I tried to reference the top node with truven$truven. It did not work.

**Comment by gluc** [comment]
Sorry for the late reply ... vacation time!

Anyway, a data.tree structure consists of `Node` objects, so the root itself is also a node. For example:

`SetNodeStyle(truven, style = "filled,rounded", shape = "box", fillcolor = "Green", fontname = "helvetica", tooltip = GetDefaultTooltip)`
