### ISSUE TITLE
Do does not work ? 

### ISSUE THREAD

**Issue by rlpatsh** [gluc/data.tree#98]
I am trying the following code from data.tree examples

    > data(acme)
    > acme$Do(function(node) node$expectedCost <- node$p * node$cost)
    > print(acme, "expectedCost")

but I am getting the below warning (converted to error). Can you please help here.. 

    Error in `[<-.data.frame`(`*tmp*`, colName, value = list(`Acme Inc.` = numeric(0),  : 
    (converted from warning) provided 11 variables to replace 1 variables
    13: (function () 
        traceback(2))()
    12: doWithOneRestart(return(expr), restart)
    11: withOneRestart(expr, restarts[[1L]])
    10: withRestarts({
            .Internal(.signalCondition(simpleWarning(msg, call), msg, 
                call))
            .Internal(.dfltWarn(msg, call))
        }, muffleWarning = function() NULL)
    9: .signalSimpleWarning("provided 11 variables to replace 1 variables", 
           quote(`[<-.data.frame`(`*tmp*`, colName, value = list(`Acme Inc.` = numeric(0), 
           Accounting = numeric(0), `New Software` = 5e+05, `New Accounting Standards` = 375000, 
               Research = numeric(0), `New Product Line` = 5e+05, `New Labs` = 675000, 
               IT = numeric(0), Outsource = 80000, `Go agile` = 12500, 
           `Switch to R` = 50000))))
    8: warning(sprintf(ngettext(ncolv, "provided %d variable to replace %d     variables", 
           "provided %d variables to replace %d variables"), ncolv, 
           p), domain = NA)
    7: `[<-.data.frame`(`*tmp*`, colName, value = list(`Acme Inc.` = numeric(0), 
           Accounting = numeric(0), `New Software` = 5e+05, `New Accounting     Standards` = 375000, 
           Research = numeric(0), `New Product Line` = 5e+05, `New Labs` = 675000, 
           IT = numeric(0), Outsource = 80000, `Go agile` = 12500, `Switch to R` = 50000))
    6: `[<-`(`*tmp*`, colName, value = list(`Acme Inc.` = numeric(0), 
           Accounting = numeric(0), `New Software` = 5e+05, `New Accounting     Standards` = 375000, 
           Research = numeric(0), `New Product Line` = 5e+05, `New Labs` = 675000, 
           IT = numeric(0), Outsource = 80000, `Go agile` = 12500, `Switch to R` = 50000))
    5: as.data.frame.Node(x, row.names = NULL, optional = FALSE, ..., 
       pruneFun = pruneFun)
    4: as.data.frame(x, row.names = NULL, optional = FALSE, ..., pruneFun = pruneFun)
    3: ToDataFrameTree(x, format = TRUE, ...)
    2: print.Node(acme, "expectedCost")
    1: print(acme, "expectedCost")

**Comment by gluc** [comment]
This has been resolved with the latest release on CRAN
