### ISSUE TITLE
Changing leaves color using Do()

### ISSUE THREAD

**Issue by ppanteliadis** [gluc/data.tree#99]
I've generated classification tree for my data, and as an extra aesthetic feature I would like to color the leaf nodes based on my prediction (Red for 0, Green for 1). 

In the following code I basically used the example documented in order to **shape** the leaves
`Do(new.tree$leaves, function(node) ifelse(node$prediction.attribute, 
                                               SetNodeStyle(node, shape = "egg"), 
                                               SetNodeStyle(node, shape = "box")))`

But when I change this code to:
```
Do(new.tree$leaves, function(node) ifelse(node$prediction.attribute, 
                                              SetNodeStyle(node, fillcolor = "Green"), 
                                              SetNodeStyle(node, fillcolor = "Red")))
```
The generated tree is ok in the terminal, but the plotted tree has no names in the values.

**Comment by gluc** [comment]
You need to use fillcolor in combination with style = filled. 

If you use e.g. `SetNodeStyle(node, fillcolor = "green")`, apparently this removes styles alltogether by the underlying DiagrammeR package, including the black fontcolor. 

If you use e.g. `SetNodeStyle(node, fontcolor =  "blue", fillcolor = "green")`, ten fillcolor is ignored.

The following works:

```
data(acme)
Set(acme$leaves, prediction.attribute = sample(c(TRUE, FALSE), acme$leafCount, TRUE))
Do(acme$leaves, function(node) ifelse(node$prediction.attribute, SetNodeStyle(node, shape = "egg"), SetNodeStyle(node, shape = "box")))

Do(acme$leaves, function(node) ifelse(node$prediction.attribute, 
                                          SetNodeStyle(node, color = "green", fontcolor = "blue", style = "filled", fillcolor = "orange"), 
                                          SetNodeStyle(node, color = "red")))

plot(acme)
```
ThisUnfortunately, DiagrammeR and the underlying graphviz libraries are huge, and I cannot document all of it in data.tree.
